### PR TITLE
NO-JIRA: Remove hack for CI in 4.11 release

### PR DESCRIPTION
**Pull request by jparrill**
Not supporting 4.11 anymore this is not needed

### CODE REVIEW

**Comment by jparrill** [comment]
Hey @sjenning do we still need this or we can drop it out?
Hey @hasueki @ryan-cradick This change could affect IBM deployments?

**Review by sjenning — APPROVED** [review]

**Comment by sjenning** [comment]
/hold
for IBM review

**Review by hasueki — APPROVED** [review]
LGTM. IBM Cloud doesn't have <4.11 clusters anymore!

**Pull request merged**
