### PR TITLE
[release-4.16] HOSTEDCP-1715: Kubernetes API Server Log Verbosity Annotation cherry pick to 4.16

### PR DESCRIPTION
**Pull request by jared-hayes-dev**
Cherry pick of #4026 on release-4.16.

#4026: rebase + merge conflicts

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by rtheis** [comment]
@jared-hayes-dev I think you'll need create a Jira and re-title this PR.

**Comment by rtheis** [comment]
@jared-hayes-dev looks like something wrong with this cherry-pick:

```
CGO_ENABLED=1 GO111MODULE=on GOFLAGS=-mod=vendor go build -gcflags=all='-N -l' -o bin/control-plane-operator ./control-plane-operator
# github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane/kas
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go:433:30: undefined: hyperv1.KubeAPIServerVerbosityLevelAnnotation
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go:434:73: undefined: hyperv1.KubeAPIServerVerbosityLevelAnnotation
make: *** [Makefile:76: control-plane-operator] Error 1
[36mINFO[0m[2024-06-08T19:08:37Z] Ran for 7m16s                                
[31mERRO[0m[2024-06-08T19:08:37Z] Some steps failed:                           
[31mERRO[0m[2024-06-08T19:08:37Z] 
```

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by jared-hayes-dev** [comment]
/retitle [release-4.16] [HOSTEDCP-1715](https://issues.redhat.com/browse/HOSTEDCP-1715) Add Annotation to customize Kubernetes API Server Log Verbosity

**Comment by jeffnowicki** [comment]
/retitle [release-4.16] HOSTEDCP-1715: Kubernetes API Server Log Verbosity Annotation cherry pick to 4.16

**Pull request merged**
