### PR TITLE
HOSTEDCP-1989: Prevent kubevirt from removing valid machine config condition

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by orenc1** [comment]
openshift-ci build issues.
/retest

**Comment by orenc1** [comment]
/retest
for konflux

**Comment by orenc1** [comment]
/retest
for konflux

**Comment by enxebre** [comment]
/override "Red Hat Konflux / hypershift-operator-main-enterprise-contract / hypershift-operator-main"

**Pull request merged**
