### PR TITLE
NO-JIRA: Remove dependency on github.com/hashicorp/go-uuid

### PR DESCRIPTION
**Pull request by mikelolasagasti**
**What this PR does / why we need it**:

This commit removes the dependency on github.com/hashicorp/go-uuid module from the project. Since the module github.com/google/uuid is already utilized in other areas of hypershift, dropping the dependency on github.com/hashicorp/go-uuid helps simplify the project's dependency graph and maintenance burden.

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@mikelolasagasti please rebase this PR so we can merge it in!

**Comment by csrwng** [comment]
/close

Closing this PR due to lack of activity. Please rebase and reopen if needed.

**Pull request closed without merging**
