### PR TITLE
OCPBUGS-38425: Return the right tagReference on Catalogs ImageStream

### PR DESCRIPTION
**Pull request by jparrill**
Which issue(s) this PR fixes :
Fixes #[OCPBUGS-38425](https://issues.redhat.com/browse/OCPBUGS-38425)

### CODE REVIEW

**Comment by bryan-cox** [comment]
@Patryk-Stefanski is this related to your PR?

**Comment by jparrill** [comment]
This PR is really attached to this other one https://github.com/openshift/hypershift/pull/4612 so if that other PR wants to be backported, we need to keep both in the same backport PR.

**Comment by jparrill** [comment]
/jira backport release-4.17,release-4.16,release-4.15,release-4.14

**Pull request merged**
