### PR TITLE
Increase timeout for nodes to get ready

### PR DESCRIPTION
**Pull request by alvaroaleman**
The current one seems to low and makes the e2e tests consistently fail
/cc @enxebre 
/test e2e-aws-all

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
to see if it actually helps

**Comment by alvaroaleman** [comment]
No, I don't know why. I had a brief look into the capi provider and there were no errors creating instances. I agree this is a bandaid fix and we need to figure out what we can do to get it to take a more acceptable amount of time, but that is probably more involved.

**Comment by enxebre** [comment]
Referenced PRs in https://github.com/openshift/hypershift/pull/1430#issuecomment-1144666152 for autoscaling and autorepair were merged.

After discussion in slack and debuging we conclude the networking issues were caused by hitting aws quotas for securityGroup rules, which prevented our network setup from finishing.
We [reduced the number of AZs](https://github.com/openshift/release/pull/29105) in the CI management cluster which automatically reduce the rules needed for LB security rules.

As a consequence of all the above the [informing Job is back green](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic).

As additional follow ups we should:
- Set up alerting on AWS that notify when quota is about to be met.
- Discuss ways to let this to be more visible somehow in the product, so no deep knowledge/debugging is needed for a user to realise a quota is impacting our ability to operate.

@alvaroaleman shall we close this now?

**Comment by alvaroaleman** [comment]
Yeah, this isn't needed anymore.

**Pull request closed without merging**
