### PR TITLE
Converge helper binaries and ignition-server into CPO binary

### PR DESCRIPTION
**Pull request by alvaroaleman**
This makes them part of the payload and thus avoids rotating most of the
controlplane when the hypershift operator gets updated.

Ref https://github.com/openshift/hypershift/issues/1156

This will break running with a CPO from release-4.10, I will submit a forwarding PR for that once this merges.

/cc @relyt0925 @csrwng 

Fixes https://github.com/openshift/hypershift/issues/1156

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
Any reason to not include ignition-server in this bucket? without including it part of the problem trying to be solved would still happen.

**Comment by sjenning** [comment]
ignition-server and CAPI are deployed from the hypershift-operator, not from the CPO.

**Comment by alvaroaleman** [comment]
> ignition-server and CAPI are deployed from the hypershift-operator, not from the CPO.

That is true but that doesn't mean we can't use the same image as the one we use for the CPO for them?

**Comment by enxebre** [comment]
>ignition-server and CAPI are deployed from the hypershift-operator, not from the CPO.

This is true for CAPI, Machine approver, Cluster autoscaler and ignition server.
Initially we decided couple building these images to the hypershift operator because it seemed the natural choice given it lifecycles running them as well but in practice I think there're some consequences that results in making the cpo/payload a better home for them:
- No need to care about productising the images, we get it for free as soon as they are in the cpo/payload.
- Mapprover and autoscaler are actually already part of the payload and their functioning is to some extend tied to the kube version of the guest cluster e.g mapprover manipulates nodes and csr and autoscaler uses scheduling and it's only tested with a given kube version per release. [So letting them come from the particular release payload for each HostedCluster makes sense](https://github.com/openshift/hypershift/pull/1090).
- For capi/capa the case above also applies since capi is getting into the payload for ocp regardless of hypershift. CAPI is also tied to the guest cluster kube version which supports n, n-1 and n2.

So the only remaining one would ignition-server. Atm a hypershift bump will cause restarting the ign-server for every HostedCluster causing a cache rebuild with the pertinent performance cost even though the code running behind the image will most likely be exactly the same most of the times. The side effect of letting it be a command of the CPO is that the release cycle will be tied to the CPO which I think is all fine. So I'm +1.

**Comment by sjenning** [comment]
sgtm as well :+1:

**Comment by alvaroaleman** [comment]
@enxebre @sjenning updated to also converge the ignition-server as well

**Comment by enxebre** [comment]
/lgtm
/hold
in case Seth had more feedback.

**Pull request merged**
