### PR TITLE
set cloud provider for kcm

### PR DESCRIPTION
**Pull request by derekwaynecarr**
set cloud provider flag on kcm.

follow-on is needed to write cloud-config files on both apiserver and kcm side.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
/hold

i expected service type loadbalancer to just work now, and its not...

**Comment by derekwaynecarr** [comment]
@csrwng when you return, i dont understand when/why we choose to use openshift-config file as the argument was not picked up from there.

anyway, this doesnt work yet as we need to render out a cloud-config file as well.

```
I0212 22:38:10.013453       1 aws.go:1251] Building AWS cloudprovider
I0212 22:38:10.013493       1 aws.go:1211] Zone not specified in configuration file; querying AWS metadata service
F0212 22:38:16.310458       1 controllermanager.go:254] error building controller context: cloud provider could not be initialized: could not init cloud provider "aws": unable to determine AWS zone from cloud provider config or EC2 instance metadata: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/placement/availability-zone": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
goroutine 268 [running]:
```

**Comment by csrwng** [comment]
@derekwaynecarr in 4.7 we're ignoring a large part of the KCM config file (actually it's not clear to me which parts we still honor). Part of the changes I made for 4.7 was to move the command line args out of the config file to the deployment

**Comment by csrwng** [comment]
For the AWS cloud config file, we'll need something like: (see [code](https://github.com/kubernetes/legacy-cloud-providers/blob/83e3ad6b3b0969b65f077b321287de3c953439a7/aws/aws.go#L588-L635))
```
[Global]
Zone = us-east-1a
VPC = vpc-020c7b5ba75402381
KubernetesClusterID = example-7890
```

**Comment by sjenning** [comment]
This works in main now
/close

**Pull request closed without merging**
