### PR TITLE
CNV-36608: Enable InPlace NodePool upgrade test for kubevirt

### PR DESCRIPTION
**Pull request by orenc1**
**What this PR does / why we need it**:
Due to an issue in nmstate in which files on the ostree filesystem have been modified, MCO could not drain the node and apply an RHCOS rollout in place.
This has been [fixed](https://github.com/nmstate/nmstate/pull/2499) in a recent release of RHCOS, thus we can enable it now.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # https://issues.redhat.com/browse/CNV-36608

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by orenc1** [comment]
@davidvossel , InPlace Upgrade for kubevirt now works.
from the [log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/3517/pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn/1754135892915654656/artifacts/e2e-kubevirt-aws-ovn/run-e2e-local/build-log.txt):
```
        --- PASS: TestNodePool/Main/TestNodePoolInPlaceUpgrade (1990.96s)
```

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by orenc1** [comment]
cherry-pick release-4.15

**Pull request merged**
