### PR TITLE
Update CAPA image to come from internal openshift CI

### PR DESCRIPTION
**Pull request by enxebre**
Needs https://github.com/openshift/release/pull/23913

### CODE REVIEW

**Comment by enxebre** [comment]
/hold
needs https://github.com/openshift/release/pull/23913

**Review by alvaroaleman — APPROVED** [review]

**Comment by csrwng** [comment]
Condition on AWSMachine:
```
 - lastTransitionTime: "2021-11-23T18:27:46Z"
    message: 'failed to create AWSMachine instance: failed to get root volume from
      image "ami-0a57c1b4939e5ef5b": no EBS returned when looking up ID "ami-0a57c1b4939e5ef5b"'
    reason: InstanceProvisionFailed
    severity: Error
    status: "False"
    type: InstanceReady
```

**Pull request merged**
