### PR TITLE
OCPBUGS-34397: Rename machine-config operator CRD references

### PR DESCRIPTION
**Pull request by Evan-Reilly**
**What this PR does / why we need it**:

Upstream machine-config-operator has renamed their CRDs https://github.com/openshift/machine-config-operator/tree/master/install. Changes in this PR should account for those changes.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes https://issues.redhat.com/browse/OCPBUGS-34397

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by bryan-cox** [comment]
Hey @Evan-Reilly @rtheis 👋🏻 - A few things:
* You'll most likely need to rebase to get rid of the Konflux failure
* You'll need to link a Jira ticket

**Comment by rtheis** [comment]
@Evan-Reilly please rebase your PR.

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by Evan-Reilly** [comment]
Added link to the Jira I created to cover the issue.  I added the basic details, but looking like I can't go back and edit it in case it needs more info.

**Comment by rtheis** [comment]
/retitle OCPBUGS-34397: Rename machine-config operator CRD references

**Comment by rtheis** [comment]
@Evan-Reilly Jeff can help you fix the Jira.

**Comment by enxebre** [comment]
Thanks
/approve

**Pull request merged**
