### PR TITLE
MULTIARCH-3708: PowerVS - Fix cluster deletion when existing resources passed

### PR DESCRIPTION
**Pull request by dharaneeshvrd**
**What this PR does / why we need it**:
[MULTIARCH-3708](https://issues.redhat.com//browse/MULTIARCH-3708): PowerVS - Fix cluster deletion when existing resources passed

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by dharaneeshvrd** [comment]
area/cli
area/testing

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
