### PR TITLE
reduce ignition server scope

### PR DESCRIPTION
**Pull request by relyt0925**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by relyt0925** [comment]
my team will pickup prs if changes are necessary (as far as commit messages, etc)

**Comment by enxebre** [comment]
Thanks!
/label tide/merge-method-squash
/approve
/lgtm

**Pull request merged**
