### PR TITLE
Add hostedClusterAvailable check for in place upgrades

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:
We should honour hosted cluster availability before trying to crete a client for it.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by alvaroaleman** [comment]
Tests are known broken, holding to prevent retest. Will unhold once they are fixed.
/hold

**Pull request merged**
