### PR TITLE
Run kube-apiserver-proxy as privileged security context

### PR DESCRIPTION
**Pull request by enxebre**
This along with https://github.com/openshift/hypershift/pull/2057/files let the pod in the kube-system ns to bind the port in the hostnework

Related to new security admission
https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-admission-labels-for-namespaces https://cloud.redhat.com/blog/pod-security-admission-in-openshift-4.11 https://docs.openshift.com/container-platform/4.11/authentication/understanding-and-managing-pod-security-admission.html#security-context-constraints-psa-opting_understanding-and-managing-pod-security-admission

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by relyt0925** [comment]
Can we try something like this
```
securityContext:
      runAsUser: 1001
      capabilities:
        add: [ "NET_BIND_SERVICE" ]
```

**Comment by relyt0925** [comment]
/hold 
Need to not be privileged and specify capabilities

**Comment by enxebre** [comment]
I'm struggling to see why this pod is failing to run without privileged.
When we run haproxy pod it also binds successfully and needs no additional perm.
```
haproxy   92622     1001    4u  IPv4 390319      0t0  TCP 172.20.0.1:443 (LISTEN)
```

```
sh-4.4$ cat /usr/local/etc/haproxy/haproxy.cfg
global
  maxconn 7000
  log stdout local0
  log stdout local1 notice

defaults
  mode tcp
  timeout client 10m
  timeout server 10m
  timeout connect 10s
  timeout client-fin 5s
  timeout server-fin 5s
  timeout queue 5s
  retries 3

frontend local_apiserver
  bind 172.20.0.1:443
  log global
  mode tcp
  option tcplog
  default_backend remote_apiserver

backend remote_apiserver
  mode tcp
  log global
  option httpchk GET /version
  option log-health-checks
  default-server inter 10s fall 3 rise 3
  server controlplane api.agl-public-private-proxy.hypershift.local:443
sh-4.4$
```

Also I question why we need the [adhoc proxy component](https://github.com/openshift/hypershift/pull/1249) at all, wouldn't set the Env PROXY variables in the haproxy pod be enough for the case described in the original PR?

re-holding myself
/hold

**Pull request closed without merging**
