### PR TITLE
Run e2e tests in parallel

### PR DESCRIPTION
**Pull request by enxebre**
Run e2e tests in parallel

### CODE REVIEW

**Comment by enxebre** [comment]
/hold
I'll update this PR to include parallelism for autoscaling test after https://github.com/openshift/hypershift/pull/374 makes it in.

**Comment by ironcladlou** [comment]
@csrwng and I tested this before and while we want to do it and it works fine, the problem is logs from all the test processes become interleaved, making it almost impossible to interpret the output when things go wrong. I'm not sure if we can easily solve it given the way logging is plumbed throughout our code and our libraries, but I hope we can.

Not sure we can merge it without a solution while we still need to rely on log output for debugging... ideas?

**Comment by enxebre** [comment]
@ironcladlou @csrwng 
I updated this to use `Testing.t Logger` instead which shows structured output. The underlying logging which in our case I believe is only for the CLI would still be unstructured but that might be acceptable.
Output example:
```
NFO[0046] Applied Kube resource                         kind=HostedCluster name=example-h6rsc namespace=e2e-clusters-dwhh6
INFO[0046] Applied Kube resource                         kind=Secret name=example-gdprs-node-mgmt-creds namespace=e2e-clusters-vnntf
INFO[0046] Applied Kube resource                         kind=NodePool name=example-h6rsc namespace=e2e-clusters-dwhh6
INFO[0046] Applied Kube resource                         kind=HostedCluster name=example-gdprs namespace=e2e-clusters-vnntf
=== CONT  TestScenarios/UpgradeControlPlane
    control_plane_upgrade.go:83: Created hostedcluster. Namespace: e2e-clusters-dwhh6, name: example-h6rsc
    control_plane_upgrade.go:96: Waiting for guest client to become available
    util.go:136: Waiting for hostedcluster kubeconfig to be published. Namespace: example-h6rsc, name: %!s(MISSING)
INFO[0047] Applied Kube resource                         kind=NodePool name=example-gdprs namespace=e2e-clusters-vnntf
=== CONT  TestScenarios/Autoscaling
    autoscaling.go:80: Found the new hostedcluster. Namespace: e2e-clusters-vnntf, name: example-gdprs
    autoscaling.go:91: Created nodepool. Namespace: e2e-clusters-vnntf, name: example-gdprs
    util.go:136: Waiting for hostedcluster kubeconfig to be published. Namespace: example-gdprs, name: %!s(MISSING)
=== CONT  TestScenarios/UpgradeControlPlane
    util.go:158: Found kubeconfig for cluster. Namespace: e2e-clusters-dwhh6, name: example-h6rsc
    util.go:177: Waiting for a successful connection to the guest apiserver
    util.go:191: successfully connected to the guest apiserver
    util.go:198: Waiting for nodes to become ready. Want: 2
```

**Comment by ironcladlou** [comment]
@enxebre @sjenning CLI output is interleaved (as expected) but it would be easy to filter down by cluster name/infra ID etc, and the actual test logs going through  the test logger look great. Let's move forward and improve as we go. Thanks for taking care of this, great testing improvement...

/hold cancel
/lgtm

**Pull request merged**
