### PR TITLE
PowerVS: upgrade capi image

### PR DESCRIPTION
**Pull request by dharaneeshvrd**
**What this PR does / why we need it**:

Trying to upgrade capi image. 

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
Let's update the go.mod as well

**Review by mkumatag — APPROVED** [review]
/lgtm

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
