### PR TITLE
OCPBUGS-38755: Remove go workspaces from source control

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
    - Removes the go.work and go.work.sum files from the repository.
    - Updates the Makefile to not use go workspaces.
    - Updates the vendored staticcheck so it won't fail on new style range
    statements.
    - Makes minor fixes flagged by staticcheck
    - Adds instructions for setting up a Go workspace in HACKING doc

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[OCPBUGS-38755](https://issues.redhat.com/browse/OCPBUGS-38755)

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by devguyio** [comment]
@csrwng can you try to explain again what was wrong with what you proposed previously? other than go.work and go.work.sum files, which other files will show up as modified that shouldn't be pushed to the repo?

**Comment by csrwng** [comment]
> can you try to explain again what was wrong with what you proposed previously? other than go.work and go.work.sum files, which other files will show up as modified that shouldn't be pushed to the repo?

The problem is trying to use those go.work files. When you run operations like `go work sync` and `go work vendor` you end up with a dirty repository.

**Comment by bryan-cox** [comment]
/retest

For konflux

**Pull request merged**
