### PR TITLE
OCPBUGS-35002: [release-4.15] HOSTEDCP-1122: Backport etcd defrag controller

### PR DESCRIPTION
**Pull request by muraee**
**What this PR does / why we need it**:
backport of https://github.com/openshift/hypershift/pull/2869

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by jparrill** [comment]
/retitle [release-4.15] HOSTEDCP-1122: Backport etcd defrag controller

**Comment by csrwng** [comment]
The kubevirt failure is not unique to this PR and is unlikely caused by it
/override ci/prow/e2e-kubevirt-aws-ovn

**Pull request merged**
