### PR TITLE
TRT-1406: Revert #3283 "HOSTEDCP-1273: Added support for OLM Disable default sources on HC creation"

### PR DESCRIPTION
**Pull request by stbenjam**
Reverts #3283 ; tracked by [TRT-1406](https://issues.redhat.com//browse/TRT-1406)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

[sig-operator] an end user can use OLM can subscribe to the operator [apigroup:config.openshift.io] is failing on hypershift conformance jobs, it looks like this is the cause

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
Verify this test passes on conformance
```

CC: @jparrill

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn-conformance

**Comment by neisw** [comment]
/lgtm

Next payload has the same failure and we can't verify this with payload command.  Adding lgtm in case you want to proceed.

**Comment by stbenjam** [comment]
/hold cancel

We don't have any other ideas, and we can't verify this PR with `/payload`.  We'll immediately unrevert this if we got it wrong.

**Comment by jparrill** [comment]
created a cherry-pick for release 4.15 to trigger the conformance tests https://github.com/openshift/hypershift/pull/3310

**Pull request merged**
