### PR TITLE
Set resource tags on endpoint services and endpoints

### PR DESCRIPTION
**Pull request by alvaroaleman**
Set resource tags on endpoint services and endpoints
    
This change makes us pass on AWS ResourceTags to the EndpointService
object and confgure them in AWS.
This change makes us:
* Add the kubernetes.io/cluster/$infraID tag to the resource tags so
   that it gets propagated to all places where we set tags instead of
   needing to add explicit logic for that everywhere
* Set the resource tags on endpoints
* Set the resource tags on endpoint services
    
ref https://issues.redhat.com/browse/HOSTEDCP-287

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold cancel

I did some nil pointer derefencing in apiTagToEC2Tag which caused the hypershift operator to crash, ptal.

**Comment by alvaroaleman** [comment]
/hold

This doesn't solve the original problem of "Tag with clutserID so infra destroy will cleanup".

**Comment by alvaroaleman** [comment]
/hold cancel

@csrwng @sjenning updated the PR to add the owned tag to the resource tags and apply the resource tags to both endpoints and endpoint services, ptal.

**Comment by alvaroaleman** [comment]
There was a staticcheck error because the same package was imported twice under different aliases, need a new lgtm.

**Comment by csrwng** [comment]
In the last e2e run the storage operator never became available, but doesn't seem related to this change.
/lgtm
/retest-required

**Comment by alvaroaleman** [comment]
@csrwng had to rebase, ptal

**Comment by alvaroaleman** [comment]
/hold
this consistently fails with rollout timeouts, seems there is an actual issue

**Comment by alvaroaleman** [comment]
The storage operator was not a fluke, this change broke it because:
* We propagate the ResourceTags to the `infrastructure`
* From there they are propagated to `extra_tags` in the aws CSI driver
* And the CSI driver will refuse any extra tags that have a `kubernetes.io` prefix

=> Fixed by omitting `kubernetes.io` tags in the `infrastructure` reconciliation. Should pass tests now, ptal.

**Comment by alvaroaleman** [comment]
/retest
/hold cancel
Testfailure seems to be caused by AWS being inconsistent, which doesn't look related to this change: `msg: "failed to create infra: cannot create NAT gateway: InvalidSubnet: The subnet ID 'subnet-0b4999fd7ea9dc05e' does not exist`

**Comment by alvaroaleman** [comment]
> failed to wait for the created cluster claim to become ready: timed out waiting for the condition 

/retest

**Pull request merged**
