### PR TITLE
Skip TestAutorepair on platforms other than AWS

### PR DESCRIPTION
**Pull request by alvaroaleman**
The test terminates an instance at the provider, this is currently only
implemented for AWS, hence it can only work on AWS.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
This, like autoscaler should work on any platform that supports automated machine management or it's a bug. Or if we don't support it for a particular platform we need to account for it in the nodepool backend and signal it in the AutorepairEnabled

**Comment by enxebre** [comment]
created https://issues.redhat.com/browse/HOSTEDCP-504

**Comment by alvaroaleman** [comment]
@enxebre I am aware, but the test doesn't. There is no reason to assume that if this does work on one platform it wouldn't work on another, as this is presumably part of the generic capi controller, which is why I don't see the value of spending time on implementing this for other providers.

**Comment by enxebre** [comment]
> @enxebre I am aware, but the test doesn't. There is no reason to assume that if this does work on one platform it wouldn't work on another, as this is presumably part of the generic capi controller, which is why I don't see the value of spending time on implementing this for other providers.

Even this is driven by provider agnostic API, Cloud providers, environments and implementations can perform differently.
It's a good thing to experience the same end users will in any platform we support and learn, without a platform e2e there is no real evidence that this works in that platform but an assumption.
The implementation of the test does not need to be provider specific, could just be a program that kills the kubelet or so. So we get the value above at a low cost.

**Comment by enxebre** [comment]
Closing for now, until we become more mature I'd prefer to be conservative, assume the costs, run more tests and hard gate on failures.
/close

**Pull request closed without merging**
