### PR TITLE
[OCPNODE-1617] Add imageDigestSources API to support IDMS 

### PR DESCRIPTION
**Pull request by QiWang19**
Signed-off-by: Qi Wang <qiwan@redhat.com>

**What this PR does / why we need it**:
The [OCPNODE-521](https://issues.redhat.com//browse/OCPNODE-521) will land new CRDs for 4.13. ICSP will continue to be functional before it gets deprecated(planned after 4.17), IDMS will replace ICSP in the future release.

Adding `imageDigestSources`, `--image-digest-sources` for the migration to use `ImageDigestMirrorSet` CRD.
Marked the `--image-content-sources` will be deprecated.

- slack discussion on update hostcontrolplane API: https://coreos.slack.com/archives/C01C8502FMM/p1659548158151629
- ImageDigestMirrorSet implemented: https://github.com/openshift/machine-config-operator/pull/3037 
- ImageDigestMirrorSet epic: https://issues.redhat.com/browse/OCPNODE-521

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # https://issues.redhat.com/browse/OCPNODE-1617
**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by QiWang19** [comment]
/hold
for 4.13 tree to open

**Comment by QiWang19** [comment]
/hold cancel
the 4.13 branch is open. This pr is ready for review

**Comment by QiWang19** [comment]
@alvaroaleman Hi, we have [discussed]( https://coreos.slack.com/archives/C01C8502FMM/p1659548158151629) the hypershift can change the API to migrate ICSP to ImageDigestMirrorSet a long time ago.
 I am working on the migration for 4.14. Could your team review this PR?

**Comment by QiWang19** [comment]
@enxebre I also pinged the team on Slack. Could you review it?

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by bryan-cox** [comment]
@QiWang19 just FYI, @/alvaroaleman left Red Hat last year I believe.

**Comment by QiWang19** [comment]
@bryan-cox I haven't tested this manually. Could someone help with the pre-merge test? Could we get this in?

**Comment by QiWang19** [comment]
close my pull request  in favor of #2437

**Pull request closed without merging**
