### PR TITLE
Reduce HyperShift operator metrics cardinality

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
To include an initial set of metrics for telemetry, this PR reduces the
number of labels to report for hosted clusters and nodepools. This is
to keep an initial set of metrics under 10 series. (5 for hc, 5 for np)

The current metric with multiple labels is also flawed in that it can
potentially count a cluster multiple times as its version or endpoint
access type changes. We will need a way to update the counts for all
possible values of each label, but this can be done at a later time.

**Checklist**
- [x] Subject and description added to both, commit and PR.

### CODE REVIEW

**Comment by enxebre** [comment]
why the bar under 10 series? does this mean we lost ability to track version, autoscaling, etc?

**Comment by csrwng** [comment]
@enxebre not necessarily. We will eventually report on those. This is just for an initial inclusion in telemetry metrics. The 10 series limitation is based on: https://docs.google.com/document/d/1a6n5iBGM2QaIQRg9Lw4-Npj6QY9--Hpx3XYut-BrUSY/edit?usp=sharing

**Comment by enxebre** [comment]
@csrwng do we have a counter part PR in telemetry to white list?

**Pull request merged**
