### PR TITLE
[release-4.15] HOSTEDCP-1518: Preserve container resource requests and limits

### PR DESCRIPTION
**Pull request by lucaspalm**
This is a manual cherry-pick of the changes from https://github.com/openshift/hypershift/pull/3864.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@lucaspalm use `UPDATE=1 go test ./...` to update fixtures:

```
 --- FAIL: TestReconcileDeployment (0.04s)
    --- FAIL: TestReconcileDeployment/No_private_apiserver_connectivity,_proxy_apiserver_address_is_set (0.02s)
        clusternetworkoperator_test.go:90: got diff between expected and actual result:
            file: /go/src/github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
            diff:
              (
              	"""
              	... // 39 identical lines
              	          value: "true"
              	        - name: HOSTED_CLUSTER_NAME
            - 	        - name: CA_CONFIG_MAP
            - 	        - name: CA_CONFIG_MAP_KEY
              	        - name: TOKEN_AUDIENCE
              	        - name: RELEASE_VERSION
              	... // 60 identical lines
              	        - /usr/bin/control-plane-operator
              	        - konnectivity-socks5-proxy
            - 	        - --disable-resolver
            + 	        - --resolve-from-guest-cluster-dns=true
              	        env:
              	        - name: KUBECONFIG
              	... // 91 identical lines
              	"""
              ) 
```

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by lucaspalm** [comment]
rebased to hopefully fix the konflux test

**Review by rtheis — APPROVED** [review]
/lgtm

**Pull request merged**
