### PR TITLE
[release-4.10] Forward from main

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:
Mostly to get the braking changes from https://github.com/openshift/hypershift/pull/1169 into the CPO
/cc @csrwng 

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
why can't this be rebased rather than `Merge branch 'main' into ff-2`?

**Comment by csrwng** [comment]
my understanding is that rebasing rewrites the history, so a previous commit (that maybe a build was based on) could disappear

**Comment by alvaroaleman** [comment]
There is one auto generated commit in this branch that isn't in main which is why it can not be fast-forwarded: https://github.com/openshift/hypershift/compare/release-4.10

And yes, as Cesar mentioned, rebasing would change the history, so that is generally not an option.

**Comment by enxebre** [comment]
To bring changes from main into your PR branch I'd expect us to be rebasing / cherry-picking from main so we don't include a merge commit in the PR and we keep the 4.10 history reasonable and meaningful. Then tests should block the PR if something is not as expected. Not a blocker to me though.

/lgtm

**Pull request merged**
