### PR TITLE
Add audit-log-maxbackup setting for openshift-api-server

### PR DESCRIPTION
**Pull request by Vincent056**
**What this PR does / why we need it**:

In order to meet CIS and PCI-DSS compliance, we need to have an audit-log-max backup set to 10 or any appropriate value, we should add this as a default so that no additional configuration is needed after the installation.

**Which issue(s) this PR fixes** *
Jira #https://issues.redhat.com/browse/OSD-15157

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
thanks! @Vincent056 where can I learn more about "CIS and PCI-DSS compliance" requirements?
/lgtm

**Comment by Vincent056** [comment]
> thanks! @Vincent056 where can I learn more about "CIS and PCI-DSS compliance" requirements? /lgtm

We have an older benchmark here: https://access.redhat.com/system/files/red_hat_openshift_4_hardening_guide_v1.1_2.pdf

The update to date benchmark can be found in: https://www.cisecurity.org/cis-benchmarks might require registration.

**Pull request merged**
