### PR TITLE
E2E: Also dump objects and logs from Hypershift namespace

### PR DESCRIPTION
**Pull request by alvaroaleman**
Currently, CI artifacts do not include the kube objects and pod logs
from the Hypershift namespace, which makes diagnosing issues where
something in the Hypershift operator went wrong difficult.

### CODE REVIEW

**Comment by sjenning** [comment]
Do we want to make it a `DumpOption`? Or just do it all the time?  My vote is just do it all the time.

Also typo in the commit msg s/dumb/dump/

**Comment by csrwng** [comment]
/hold
sorry missed your comment @sjenning

**Comment by alvaroaleman** [comment]
> Do we want to make it a DumpOption? Or just do it all the time? My vote is just do it all the time.

@sjenning the reason I gated it is that `dump` is a per-cluster cmd and these are the logs for all clusters, WDYT? I am ok either way

**Pull request merged**
