### PR TITLE
OCPBUGS-32191: Kas disable audit cherry pick release 4.15

### PR DESCRIPTION
**Pull request by Joseph-Goergen**
related: https://github.com/openshift/hypershift/issues/3764

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by rtheis** [comment]
https://github.com/openshift/hypershift/pull/3765

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by rtheis** [comment]
@Joseph-Goergen please investigate the test failure to see if it it is related to your changes.

**Comment by Joseph-Goergen** [comment]
@sjenning Can we get some help on this `e2e-kubevirt-aws-ovn` test? I'm looking at some of the logs of the test and it doesn't seem related to my PR, but it's failed quite a bit.

**Review by rtheis — APPROVED** [review]
/lgtm

**Pull request merged**
