### PR TITLE
app-sre artifacts for image building and saas deployments

### PR DESCRIPTION
**Pull request by geoberle**
adding scripts for image building and installation-template generation with AppSREs [qontract-reconcile](https://github.com/app-sre/qontract-reconcile)

running `make app-sre-saas-template` generates the operator installation manifests with `hypershift install --render` and wraps them into an [Openshift template](https://docs.openshift.com/container-platform/4.9/openshift_images/using-templates.html). a fresh build of current hypershift sources is used for the installation manifest generation. the resulting template is placed under `hack/app-sre/saas_template.yaml` and offers parameters for the actual
container image to use on template instantiation.

the hack/app-sre/build_push.sh script is used in AppSREs CI. it will
* build the image with `make docker-build`
* verify that the template is up to date in regards to the current hypershift build
* tag the image and push it to quay.io/app-sre/hypershift-operator:${7-char-commit_sha}

the CI build in AppSREs build enviroment will fail if the `install --render` output does not align with the template stored under `hack/app-sre/saas_template.yaml`. it is the responsibility of the author of a change to call `make app-sre-saas-template` and commit changes to the resulting `saas_template.yaml` along with the changes to hypershift itself.

the only tooling required to run the make target and the build script is docker or podman.

Part of: https://issues.redhat.com/browse/HOSTEDCP-298 and https://issues.redhat.com/browse/APPSRE-4240

Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>

### CODE REVIEW

**Comment by csrwng** [comment]
I think it's fine to introduce the static template to get us going, but for us the source of truth is the CLI, so we need to have an easy way to verify that the static template is up to date (via `make verify`) and to update the static template whenever it gets out of date. For that, it'd be great if we can support something like a `hypershift install --render-template` flag that will render the resources in template format.

@geoberle can you describe what changes you needed to make to the output of `hypershift install --render` to create the template?

**Comment by geoberle** [comment]
> I think it's fine to introduce the static template to get us going, but for us the source of truth is the CLI, so we need to have an easy way to verify that the static template is up to date (via `make verify`) and to update the static template whenever it gets out of date. For that, it'd be great if we can support something like a `hypershift install --render-template` flag that will render the resources in template format.
> 
> @geoberle can you describe what changes you needed to make to the output of `hypershift install --render` to create the template?

the app-interface SAAS process requires static templates stores in the code repo of the software it manages.

the make target introduced with this PR is doing the generation of the template from the output of `install --render`. the idea is that the author of a commit runs that target before committing anything new that changes the output of `--render`. changes to the generated target are then committed along with the code that is responsible for the change. in order to catch situation where this step has been forgotten, the [AppSRE pipeline script](https://github.com/openshift/hypershift/blob/f9e7d3d6872732f1293f8a332be2cb2af48831c6/hack/app-sre/build_push.sh) notices differences by comparing the output of the freshly build hypershift image with the template stored in the repo.

the changes to the plain output of `install --render` are rather simple. the manifests are wrapped into the `objects` list of an openshift template. the image used by the operator deployment needs to be parameter placeholders,  namely `REGISTRY_IMG` and `IMAGE_TAG`. i was also trying to add some labels to the `ServiceMonitor` and `PrometheusRule` resources so they can be picked up by AppSREs prometheus instance. you can see the generation process [here](https://github.com/openshift/hypershift/blob/f9e7d3d6872732f1293f8a332be2cb2af48831c6/hack/app-sre/generate-saas-template.py).

**Comment by csrwng** [comment]
Thank you @geoberle, that makes sense!
Can you please add the `app-sre-saas-template` to the `verify` target so we fail verification if the template needs to be generated?
https://github.com/openshift/hypershift/blob/8ec82738ec21f10c36355ddfd06eae7e29c574fd/Makefile#L44

**Comment by ironcladlou** [comment]
@csrwng @enxebre @alvaroaleman @sjenning 

Would it make sense for us to have something like a `hypershift install render` subcommand which supports the following output formats:

1. `yaml` (the current implementation)
2. `openshift-template`

I am hesitant to introduce any non-Go transformations outside the `install` command to manage the output going forward.

**Comment by ironcladlou** [comment]
> @csrwng @enxebre @alvaroaleman @sjenning
> 
> Would it make sense for us to have something like a `hypershift install render` subcommand which supports the following output formats:
> 
> 1. `yaml` (the current implementation)
> 2. `openshift-template`
> 
> I am hesitant to introduce any non-Go transformations outside the `install` command to manage the output going forward.

I'd be willing to implement that using this PR as a guide.

**Comment by ironcladlou** [comment]
We could also use this PR as the MVP to test integrations and refactor into Go as a followup.

**Comment by csrwng** [comment]
> We could also use this PR as the MVP to test integrations and refactor into Go as a followup.

That makes sense to me

**Comment by geoberle** [comment]
> @csrwng @enxebre @alvaroaleman @sjenning
> 
> Would it make sense for us to have something like a `hypershift install render` subcommand which supports the following output formats:
> 
> 1. `yaml` (the current implementation)
> 2. `openshift-template`
> 
> I am hesitant to introduce any non-Go transformations outside the `install` command to manage the output going forward.

that would be great. this way we could get rid of the python script!

**Comment by enxebre** [comment]
mvp and follow up sgtm @ironcladlou.
@geoberle please let's make sure to squash commits once all comments are addressing before merging

**Comment by geoberle** [comment]
> Thank you @geoberle, that makes sense! Can you please add the `app-sre-saas-template` to the `verify` target so we fail verification if the template needs to be generated?

done

**Comment by csrwng** [comment]
/lgtm
We will add the verify target once we switch to go-based template generation

**Comment by csrwng** [comment]
```
NoClusters: No clusters in pool are ready to be claimed 
```
:( 
/approve
/retest

**Pull request merged**
