### PR TITLE
OCPBUGS-30574: Update OLM Default Catalog Sources to 4.16 on main

### PR DESCRIPTION
**Pull request by orenc1**
4.16 default olm catalog sources are available already, so we can now update the default catalog sources to point to 4.16 indices instead of 4.14.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by bryan-cox** [comment]
/retest

For Konflux test

**Comment by orenc1** [comment]
> /retest
> 
> For Konflux test

PVC quota exceeded, I'll ask for RHTAP support.

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Pull request merged**
