### PR TITLE
Always set TokenSecretReasonKey/TokenSecretMessageKey

### PR DESCRIPTION
**Pull request by enxebre**
https://github.com/openshift/hypershift/pull/1873
This mistakenly prevent the TokenSecretMessageKey/TokenSecretReasonKey from being set in replace upgrades.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
cc @hasueki

**Review by hasueki — APPROVED** [review]

**Pull request merged**
