### PR TITLE
HOSTEDCP-1343: docs(ibmcloud): Add HC/HCP yamls for IBM Cloud

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Supersedes:
- https://github.com/openshift/hypershift/pull/2841
- https://github.com/openshift/hypershift/pull/2842
- https://github.com/openshift/hypershift/pull/2843
- https://github.com/openshift/hypershift/pull/2844
- https://github.com/openshift/hypershift/pull/2845

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by bryan-cox** [comment]
@hasueki - This looks good to me overall, but you'll need a Jira ticket for it. Do you have access to make that? If not, I can make it for you.

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Review by csrwng — COMMENTED** [review]
Just a nit

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
