### PR TITLE
MULTIARCH-3449: set priority class for cloud controller manager pod for PowerVS

### PR DESCRIPTION
**Pull request by dharaneeshvrd**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

Fixes [MULTIARCH-3449](https://issues.redhat.com//browse/MULTIARCH-3449)

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by dharaneeshvrd** [comment]
area/control-plane-operator

**Comment by dharaneeshvrd** [comment]
cc @mkumatag

**Review by mkumatag — COMMENTED** [review]
/lgtm

**Pull request merged**
