### PR TITLE
OCPBUGS-37179: OCPBUGS-38165: E2E test to verify openshift-apiserver TLS certificates

### PR DESCRIPTION
**Pull request by jparrill**
Manual backport of [OCPBUGS-35905](https://issues.redhat.com/browse/OCPBUGS-35905)

**Which issue(s) this PR fixes**:
Fixes #[OCPBUGS-37179](https://issues.redhat.com/browse/OCPBUGS-37179)

### CODE REVIEW

**Review by sjenning — CHANGES_REQUESTED** [review]
https://github.com/openshift/hypershift/pull/4507#issuecomment-2339530575

**Comment by jparrill** [comment]
As we have now gated e2e tests for every release, this is not necessary anymore.
/close

**Pull request closed without merging**
