### PR TITLE
[release-4.13] HOSTEDCP-1010: Set ETCD Storage Size as immutable field and equalised the default size among both api versions

### PR DESCRIPTION
**Pull request by jparrill**
Manual cherry-pick from https://github.com/openshift/hypershift/pull/2588

**Which issue(s) this PR fixes**:
Fixes #[HOSTEDCP-1010](https://issues.redhat.com/browse/HOSTEDCP-1010)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by jparrill** [comment]
/assign jparrill

On Hold until the summit week ends
/hold

**Comment by enxebre** [comment]
/lgtm
/approve
/hold
post summit.

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
