### PR TITLE
OCPBUGS-16125: [release-4.13] Update vendored dependencies

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
Ran the following commands:
- go get -v golang.org/x/net@latest

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[OCPBUGS-16125](https://issues.redhat.com/browse/OCPBUGS-16125)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by csrwng** [comment]
Ended up updating only `golang.org/x/net@latest` because updating the openshift-api causes issues with the cluster-api vendored code.

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
