### PR TITLE
AUTH-323: pki: remove root-ca from the client CA bundle

### PR DESCRIPTION
**Pull request by stlaz**
This is a continuation of the client-cert trust split.

/assign @csrwng
/cc @ibihim

### CODE REVIEW

**Comment by stlaz** [comment]
/test e2e-aws

I am not exactly sure how the client in the`TestUpgradeControlPlane/EnsureNodeCountMatchesNodePoolReplicas` is constructed or which client it is.

Trying to retest if this was a random failure.

**Comment by stlaz** [comment]
Since the combined-ca CM is still present in the NS with the cluster being upgraded it would seem that we're still upgrading from a version that did not contain the signer changes, and therefore the former client cert is signed by the root CA.

Based on the above, it makes sense that the pre-upgrade client cannot be used post-upgrade. I am not sure if re-retrieving the client after the upgrade would make things work as I would suspect that the kubeconfig the test is using will be the same.

**Comment by stlaz** [comment]
I noticed that the same guest client was used before and after the upgrade. Fixed that in the last commit, let's see if the situation improves.

**Comment by stlaz** [comment]
The previous issue is now fixed. The test only fails because there were some restarting pods - these restarted because they could no longer authenticate, but they managed to recover to become working in their last revision.

**Comment by csrwng** [comment]
@stlaz my only concern is that servicemonitors/podmonitors will once again be broken because we still have some metrics serving certs signed by root-ca. I had switched them to the total-client-ca here: https://github.com/openshift/hypershift/pull/1896. For this not to break them, we'd need a separate bundle that includes the root-ca (for now) just for the servicemonitors

**Comment by stlaz** [comment]
@csrwng from my understanding of https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.TLSConfig, https://github.com/openshift/hypershift/pull/1896 has likely broken metrics scraping.

Metrics serving certs should remain being signed by the root-ca. In your PR, you are setting the TLSConfig.CA to the Client-CA, but the documentation states that this configuration is used to verify the serving certs of the probed endpoint. This should've stayed RootCA.

The client certificate in the meantime is signed by the client-CA, and so these should remain in the configs.

**Comment by stlaz** [comment]
The "TestUpgradeControlPlane/EnsureNoCrashingPods" test will not pass until the "upgraded-from" version has the services signed by the new signers.

Note that the upgraded pods are actually not crashing, just restarting to get the correct certificates.

**Comment by stlaz** [comment]
/retest-required
flakes

**Pull request merged**
