### PR TITLE
Release 4.8 20210107

### PR DESCRIPTION
**Pull request by relyt0925**

### CODE REVIEW

**Comment by enxebre** [comment]
This PR is including a [commit which messages is "up"](https://github.com/openshift/hypershift/pull/831/commits/3115664925ad6e470dfbd4cafda3fa3084d103cf)

[and a commit which is a merged from main](https://github.com/openshift/hypershift/pull/831/commits/f8255421ab22884f2b78f056aad90ae07567fc9a)

Can we please drop both? Also can you please include in the PR desc the git process followed to come up with the list of cherry picks included in the PR?

**Comment by relyt0925** [comment]
We need the merge commit to stay in sync with changes with the main branch. I am ok in renaming the up commit though and will do that.

**Comment by enxebre** [comment]
> We need the merge commit to stay in sync with changes with the main branch.

Can we please do it via rebase so we keep a cleaner git history?

> I am ok in renaming the up commit though and will do that.

Where is that coming from? is it in main?

**Comment by relyt0925** [comment]
I’m not sure if rebasing is going to make the weekly sync harder…… I might be wrong but I typically have been doing the weekly pull from main
git pull origin main and then looking through the changes and regression testing 4.8. I’m hesitant (might be overthinking it though) to try and do rebase instead with the only reason mainly being I don’t want to make that merge process harder than it already is (pretty high touch right now to analyze the commits and ensure everything is comptaible. Mainly don’t additionally want to get into dealing with large merge conflicts a lot of the time.


I pushed the up commit to try and get the pr testing back to being operational. There were 4.10 images and it didn't necessarily seem right to have them in the 4.8 branch but I think it's fine to do so (specifically the docker images:
 https://github.com/openshift/hypershift/pull/831/commits/3115664925ad6e470dfbd4cafda3fa3084d103cf)

**Comment by enxebre** [comment]
Thanks @relyt0925 - Discussed on slack and agreed to keep the merge to prevent the sync process from becoming more complicated. fwiw This is excepcional situation, once we cut an official release we will honour back-port policy and only cherry-pick curated bug fixes tracked in bugzilla.

**Pull request merged**
