### PR TITLE
DNM: Machine config server authentication

### PR DESCRIPTION
**Pull request by relyt0925**
Port of: https://github.com/openshift/hypershift/pull/92

Integrates a haproxy side car server with the machine config server that can enable it to do authentication using the node bootstrapper token.

Adds a controller that handles syncing any changes to the node bootstrapper token in a user cluster to the control plane and updating of the asssociated user-data secret to update the auth for the initial call workers use to auth to the ignition server.

Moves the ignition route to have E2E tls validation. CAs are passed to the user-data that workers use to make the initial ignition call to validate TLS.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Can someone help me understand why we need to orchestrate haproxy with configuration templating in order to secure a low volume HTTP endpoint? This seems like a massive step backwards. With all the native API driven programmable servers/proxies available to us, why would we want to ship and support haproxy in this context? What alternatives were considered? I would speculate that the Go stdlib HTTP server would be more than sufficient for this task until proven otherwise.

I think we need to have a discussion about the requirements here.

**Comment by ironcladlou** [comment]
Thinking about this again, it does occur to me that the larger architectural question about MCS in this case is outside the scope of this PR's proposal and I'm moving that discussion elsewhere. What you have here assumes we continue to use MCS for the purpose and expands upon it, which seems reasonable.

If we're going to continue building on MCS for this, configuring it via its own mechanisms (the raw HAproxy config template) would make sense. I would still ask that we wait for @csrwng's overarching refactor in the controller and then make this fit the pattern.

**Comment by sjenning** [comment]
pretty sure this is superseded by https://github.com/openshift/hypershift/pull/248

**Pull request closed without merging**
