### PR TITLE
OCPBUGS-24308: Add PodDisruptionBudget for router deployment

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
The router deployment is in the request serving path and should be protected from outages by a PDB like the other request serving components

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[OCPBUGS-24308](https://issues.redhat.com/browse/OCPBUGS-24308)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by wking** [comment]
/retitle OCPBUGS-24308: Add PodDisruptionBudget for router deployment

**Comment by wking** [comment]
[e2e-aws][1] looks good:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hypershift/3337/pull-ci-openshift-hypershift-main-e2e-aws/1737131747058913280/artifacts/e2e-aws/run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-2vml6-example-cqn8m/hypershift.openshift.io/hostedcontrolplanes/example-cqn8m.yaml | grep ' controllerAvailabilityPolicy:'
  controllerAvailabilityPolicy: SingleReplica
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hypershift/3337/pull-ci-openshift-hypershift-main-e2e-aws/1737131747058913280/artifacts/e2e-aws/run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-2vml6-example-cqn8m/policy/poddisruptionbudgets/router.yaml | grep -A100 '^status:'
status:
  conditions:
  - lastTransitionTime: "2023-12-19T15:52:49Z"
    message: ""
    observedGeneration: 1
    reason: SufficientPods
    status: "True"
    type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/3337/pull-ci-openshift-hypershift-main-e2e-aws/1737131747058913280

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
