### PR TITLE
docs: refactor agent documentation

### PR DESCRIPTION
**Pull request by sjenning**
**What this PR does / why we need it**:

The existing agent documentation goes into too much detail on things that are not on the fast path to success and covers things that should be covered elsewhere such as "how to install golang".

It also implies that a metal IPI OCP cluster with bare metal operator are required when they are not.

This tries to streamline the agent docs to put users on a fast path to success.

There are still some things that need cleaned up like the use of 3rd party `tasty` tool, but leaving that for another day.

@csrwng @enxebre @eranco74 

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by csrwng** [comment]
This lgtm, but would like @eranco74 or @avishayt to take a look as well

**Comment by sjenning** [comment]
FYI, best way to review is the preview https://deploy-preview-1466--hypershift-docs.netlify.app/how-to/agent/create-agent-cluster/

**Comment by enxebre** [comment]
nice! lgtm as well.

**Review by avishayt — APPROVED** [review]

**Pull request merged**
