### PR TITLE
OCPBUGS-33428: Complete KAS migration to none endpoint reconciler type

### PR DESCRIPTION
**Pull request by rtheis**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # https://issues.redhat.com/browse/OCPBUGS-33428

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by jparrill** [comment]
Thanks for the PR. I like the change but did we validate the behaviour now is the expected one in the KAS reconciler we do in the CPO?

**Comment by rtheis** [comment]
/retest-required

> Thanks for the PR. I like the change but did you validate the behaviour now is the expected one in the KAS reconciler we do in the CPO?

@jparrill I did validate this behavior changes.  See https://issues.redhat.com/browse/OCPBUGS-33428 for the related test and verification information.

**Comment by jparrill** [comment]
Hey @rtheis did you find anything relevant?

**Comment by rtheis** [comment]
@jparrill thanks to Cesar's help, I pushed an update that I hope will resolve the test failure.

**Comment by jparrill** [comment]
@rtheis Cool! let me approve it.
/approve

**Pull request merged**
