### PR TITLE
[release-4.13] HOSTEDCP-926: Send metric when HO/CPO decide to skip cloud resource deletion

### PR DESCRIPTION
**Pull request by jparrill**
Manual cherry-pick from https://github.com/openshift/hypershift/pull/2531

/assign jparrill
/area hypershift-operator
/area control-plane-operator
/hold

### CODE REVIEW

**Comment by sjenning** [comment]
/lgtm
/approve
Not sure what the hold is for, but I assume it is to wait for PR to merge on `main`, which is has

**Comment by jparrill** [comment]
> /lgtm /approve Not sure what the hold is for, but I assume it is to wait for PR to merge on `main`, which is has

Talking with @csrwng, we agreed to wait until the Summit event finishes.

**Pull request merged**
