### PR TITLE
CNF-12792:nto: add configmaps/finalizers under operator `Role`

### PR DESCRIPTION
**Pull request by Tal-or**
**What this PR does / why we need it**:
NTO is watching for the `ConfigMap` that encpasulets the `PerformanceProfile` and creates different components based on the given profile.

We should block the `PerformanceProfile` deletion as long as the dependent components exist.

For that NTO needs access the finalizers of the `ConfigMap`.

We should also update the control plane operator since
it's its responsibility to update NTO's role.

**Which issue(s) this PR fixes**
Fixes # [CNF-11559](https://issues.redhat.com/browse/CNF-11559)

### CODE REVIEW

**Comment by sjenning** [comment]
This needs to be added to the control-plane-operator role as well.
```
failed to update control plane: failed to reconcile cluster node tuning operator: failed to reconcile cluster node tuning operator role: roles.rbac.authorization.k8s.io \"cluster-node-tuning-operator\" is forbidden: user \"system:serviceaccount:e2e-clusters-5526g-example-tm6z7:control-plane-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:e2e-clusters-5526g-example-tm6z7\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"configmaps/finalizers\"], Verbs:[\"*\"]}"
```

**Comment by Tal-or** [comment]
> This needs to be added to the control-plane-operator role as well.
> 
> ```
> failed to update control plane: failed to reconcile cluster node tuning operator: failed to reconcile cluster node tuning operator role: roles.rbac.authorization.k8s.io \"cluster-node-tuning-operator\" is forbidden: user \"system:serviceaccount:e2e-clusters-5526g-example-tm6z7:control-plane-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:e2e-clusters-5526g-example-tm6z7\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"configmaps/finalizers\"], Verbs:[\"*\"]}"
> ```

Thank you @sjenning updated as requested PTAL

**Comment by Tal-or** [comment]
I added the permissions to the control plane operator but the error persist:
```
    hypershift_framework.go:395: ReconciliationSucceeded, Reason: ReconciliationError, Message: failed to reconcile control plane operator: failed to reconcile controlplane operator role: roles.rbac.authorization.k8s.io "control-plane-operator" is forbidden: user "system:serviceaccount:hypershift:operator" (groups=["system:serviceaccounts" "system:serviceaccounts:hypershift" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
        {APIGroups:[""], Resources:["configmaps/finalizers"], Verbs:["*"]}
```

**Comment by Tal-or** [comment]
> I added the permissions to the control plane operator but the error persist:
> 
> ```
>     hypershift_framework.go:395: ReconciliationSucceeded, Reason: ReconciliationError, Message: failed to reconcile control plane operator: failed to reconcile controlplane operator role: roles.rbac.authorization.k8s.io "control-plane-operator" is forbidden: user "system:serviceaccount:hypershift:operator" (groups=["system:serviceaccounts" "system:serviceaccounts:hypershift" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
>         {APIGroups:[""], Resources:["configmaps/finalizers"], Verbs:["*"]}
> ```

@sjenning Could you please have take a look? it seems like the hypershift operator needs some additional permissions as well but I couldn't find the relevant files

**Comment by Tal-or** [comment]
The failure doesn't seems related to this PR and also reproduced on other PRs [here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4033/pull-ci-openshift-hypershift-main-e2e-azure/1790490677897859072)
```
error: timed out waiting for the condition on hostedclusters/400b93ce3e99541261a6-mgmt
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-05-15T08:15:19Z"}
error: failed to execute wrapped command: exit status 1
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/create-management-cluster
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=hypershift&branch=main&test=e2e-azure, "e2e-azure" post steps failed: "e2e-azure" pod "e2e-azure-destroy-management-cluster" failed: could not watch pod: the pod ci-op-k9wjbwri/e2e-azure-destroy-management-cluster failed after 40m11s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
enshift/hypershift/cmd/cluster/core.waitForRestOfFinalizers
	/hypershift/cmd/cluster/core/destroy.go:198
github.com/openshift/hypershift/cmd/cluster/core.DestroyCluster
	/hypershift/cmd/cluster/core/destroy.go:119
github.com/openshift/hypershift/cmd/cluster/azure.DestroyCluster
	/hypershift/cmd/cluster/azure/destroy.go:71
github.com/openshift/hypershift/cmd/cluster/azure.NewDestroyCommand.func1
	/hypershift/cmd/cluster/azure/destroy.go:41
github.com/spf13/cobra.(*Command).execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:920
github.com/spf13/cobra.(*Command).ExecuteC
	/hypershift/vendor/github.com/spf13/cobra/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	/hypershift/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext
	/hypershift/vendor/github.com/spf13/cobra/command.go:961
main.main
	/hypershift/main.go:70
```

**Comment by stevekuznetsov** [comment]
@openshift/openshift-team-hypershift

**Pull request merged**
