### PR TITLE
Add cloud.ibm.com into konnectivity cloudAPI

### LINKED ISSUE #1738: Issue in PowerVS cluster deletion cleanup - ingresscontroller cleanup
Trying to delete powervs cluster with clean up flag `--destroy-cloud-resources`. Where deletion is stuck on ingress-operator on deleting the dnsrecords.

While making GET or POST API to IBM Cloud to retrieve dnsrecord list, getting `EOF` or `net/http: TLS handshake timeout`

`"error": "delete: failed to list the dns record: An error occurred while performing the 'authenticate' step: Post \"https://iam.cloud.ibm.com/identity/token\": EOF", "errorCauses": [{"error": "delete: failed to list the dns record: An error occurred while performing the 'authenticate' step: Post \"https://iam.cloud.ibm.com/identity/token\": EOF"}, {"error": "delete: failed to list the dns record: An error occurred while performing the 'authenticate' step: Post \"https://iam.cloud.ibm.com/identity/token\": EOF"}]`

Few points to note:
1. Not facing this issue on plain destroy without the clean up flag.
2. Not facing this issue in AWS cluster deletion with the cleanup flag.
3. While the cluster is up deleting the dnsrecord is working fine. Tried deleting the default dnsrecord of default ingress controller, able to see its getting recreated in both guest cluster as well as in IBM Cloud CIS.

Adding IBM Cloud endpoints to `NoProxy` env var solves the problem. 
But not sure why it's not happening in AWS case.

### PR DESCRIPTION
**Pull request by dharaneeshvrd**
**What this PR does / why we need it**:

fixes #1738 
fixes https://issues.redhat.com/browse/MULTIARCH-2795
fixes https://issues.redhat.com/browse/HOSTEDCP-568

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by dharaneeshvrd** [comment]
> Please use
> 
> https://github.com/openshift/hypershift/blob/cb7c55daf7f06d46eddbdbaa529c1593ace58640/konnectivity-socks5-proxy/main.go#L263
> 
> consistently with other platforms.
> See https://issues.redhat.com/browse/HOSTEDCP-568

We had a discussion regarding adding ibmcloud endpoints to exceptional list in the quoted func. But @relyt0925

**Comment by dharaneeshvrd** [comment]
@enxebre I have added cloud.ibm.com into konnectivity isCloudAPI func(), ptal!

**Comment by enxebre** [comment]
/approve
cc @csrwng @relyt0925 https://github.com/openshift/hypershift/pull/1741#issuecomment-1254883243

**Pull request merged**
