### PR TITLE
OCPBUGS-18127: Ensure machineTemplate name length respects RFC1123 spec

### PR DESCRIPTION
**Pull request by muraee**
**What this PR does / why we need it**:
follow-up of https://github.com/openshift/hypershift/pull/2956 

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by jparrill — COMMENTED** [review]
/lgtm

**Comment by csrwng** [comment]
/hold
How will old templates be garbage collected?

**Comment by sjenning** [comment]
/hold
https://github.com/openshift/hypershift/pull/2981

**Comment by sjenning** [comment]
/hold cancel
https://github.com/openshift/hypershift/pull/2988 is fixing high HO reads issue

**Pull request merged**
