### PR TITLE
OSASINFRA-3567: openstack: fix setting external DNS on create

### PR DESCRIPTION
**Pull request by mdbooth**
**What this PR does / why we need it**:

We were setting externalDNSDomain in completedCreateOptions, but reading it
from RawCreateOptions, so the value we were using was never set.

We have been unable to make external-dns-domain work correctly, so for now we remove support for it and add a validation that it is not set so we can safely fix it later.

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.
- [x] Create a bug in OSASINFRA

### CODE REVIEW

**Comment by EmilienM** [comment]
Thanks for fixing this, that was indeed an error in the initial CLI PR.
/lgtm
/hold for CI
e2e-openstack needs to pass first.

**Comment by mdbooth** [comment]
Some console logs captured from a failing node:
```
[ 1477.795562] ignition[822]: GET error: Get "https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition": net/http: TLS handshake timeout
[ 1482.800859] ignition[822]: GET https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition: attempt #100
[ 1492.821930] ignition[822]: GET error: Get "https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition": net/http: TLS handshake timeout
[ 1497.822514] ignition[822]: GET https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition: attempt #101
[ 1507.844494] ignition[822]: GET error: Get "https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition": net/http: TLS handshake timeout
[ 1512.848844] ignition[822]: GET https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition: attempt #102
[ 1522.870240] ignition[822]: GET error: Get "https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition": net/http: TLS handshake timeout
[ 1527.870582] ignition[822]: GET https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition: attempt #103

> host ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com
ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com has address 54.175.78.89
ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com has address 44.205.63.74
ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com has address 52.7.146.137

> curl https://ignition-example-jwzsl.service.ci.hypershift.devcluster.openshift.com/ignition
```

Note that the curl hung.

**Comment by EmilienM** [comment]
bot went sleep...
/test e2e-aws e2e-kubevirt-aws-ovn-reduced

**Pull request merged**
