### PR TITLE
OCPBUGS-44041: add --skip-service-principal-deletion flag

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**
**What this PR does / why we need it**:

-  adds --skip-service-principal-deletion flag to remove az cli dependency when deleting clusters

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by fxierh** [comment]
/retitle OCPBUGS-44041: add --skip-service-principal-deletion flag

**Comment by bryan-cox** [comment]
Would you add the why to the commit message please?

**Comment by fxierh** [comment]
Built an image from this PR and successfully tested it in the CI:
https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/pr-logs/pull/openshift_release/58325/rehearse-58325-periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-azure-aks-hypershift-ephemeral-creds-guest-f7/1856755264057774080

**Pull request merged**
