### PR TITLE
[release-4.10] Ensure that everything uses imagePullPolicy IfNotPResent for resiliency

### LINKED ISSUE #1182: Operations: ensure imagePullPolicies are IfNotPresent for better tolerance of networking outages
We should change the image pull policy for all components (besides the catalog operators to be `IfNotPresent` to be able to better tolerate registry outages. With this change: components that were already running and had the image cached on the node would be able to restart and start new pods even if the downstream registry is down. 

This will help tangibly with the Satellite disconnected use case where customers will disconnect their locations from the public internet for a period of time.  

Note: 
Any openshift image that pulls by sha256 does not need to have this change..... (those will still work either way)

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Manual cherry-pick of https://github.com/openshift/hypershift/pull/1304

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #1182, https://issues.redhat.com/browse/HOSTEDCP-330

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by csrwng** [comment]
```
    util.go:306: container manager in pod cluster-api-7bffb7cf69-26rxq has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container manager in pod cluster-api-7bffb7cf69-c7jjr has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container manager in pod cluster-api-7bffb7cf69-ftc2j has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container control-plane-operator in pod control-plane-operator-fc48775df-vss8k has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container hosted-cluster-config-operator in pod hosted-cluster-config-operator-8589c5ffb8-sqt4z has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container konnectivity-agent in pod konnectivity-agent-7ff9b9b87f-8hm2f has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container konnectivity-agent in pod konnectivity-agent-7ff9b9b87f-96dt2 has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container konnectivity-agent in pod konnectivity-agent-7ff9b9b87f-vlzmb has doesn't have imagePullPolicy IfNotPresent but Always
    util.go:306: container konnectivity-server in pod konnectivity-server-6f9dd5b57f-vzbds has doesn't have imagePullPolicy IfNotPresent but Always
```

**Review by alvaroaleman — APPROVED** [review]
/hold cancel

**Pull request merged**
