### PR TITLE
Complete removal of manifest bootstrapper

### PR DESCRIPTION
**Pull request by csrwng**
Moves reconciliation of resources that need to be applied to the guest
cluster to the hosted cluster config operator and completely removes the
need for a manifest bootstrapper pod.

### CODE REVIEW

**Comment by enxebre** [comment]
/lgtm
/hold

Feel free to cancel the hold.

**Comment by alvaroaleman** [comment]
Looks good, but since this is a huge change there is a good chance something gets missed so I'd like to see the conformance tests pass against this before we merge. Would you mind waiting for https://github.com/openshift/release/pull/24556 so we can run them?

**Comment by csrwng** [comment]
This is a new failure mode:
```
Unable to connect to the server: dial tcp: lookup adc548386b8924f0d958170aab04cb2c-168144485.us-east-1.elb.amazonaws.com on 172.30.0.10:53: no such host
```
(on the management cluster)
/test e2e-conformance

**Comment by csrwng** [comment]
@ironcladlou I added a commit with documentation updates

**Comment by ironcladlou** [comment]
Awesome, thanks!

/lgtm

**Comment by sjenning** [comment]
conformance test is currently busted
/hold cancel

**Pull request merged**
