### PR TITLE
Remove CAPI manager container command path

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it**:
Removes CAPI manager container command path since it can differ based on release image used.

**Which issue(s) this PR fixes**
N/A

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by hasueki — APPROVED** [review]
This may not cover all use cases of overriding the CAPI image, but this will work for us.

**Comment by a-dsouza** [comment]
@csrwng Could you please help verify if these failures are related to the changes here?

**Comment by csrwng** [comment]
@bryan-cox my one concern with this is that if we would not be able to override the image using the image from a release payload. Why not just not specify the command for the deployment? I've looked at the image we had before and the one from the payload and they each have the correct entry-point in the metadata. So if we don't specify a command, they should "just work"

**Pull request merged**
