### PR TITLE
OCPBUGS-37178: E2E test to verify openshift-apiserver TLS certificates

### PR DESCRIPTION
**Pull request by jparrill**
Manual backport of [OCPBUGS-35905](https://issues.redhat.com/browse/OCPBUGS-35905)

**Which issue(s) this PR fixes**:
Fixes #[OCPBUGS-37178](https://issues.redhat.com/browse/OCPBUGS-37178)

### CODE REVIEW

**Comment by sjenning** [comment]
/hold
There isn't a lot of value backporting pure e2e PRs and soon, hopefully, we'll use e2e from `main` against all branches.  Let's stop backporting this any farther.

**Comment by jparrill** [comment]
> /hold There isn't a lot of value backporting pure e2e PRs and soon, hopefully, we'll use e2e from `main` against all branches. Let's stop backporting this any farther.

👍 Thanks for the heads up

**Comment by jparrill** [comment]
Once we have the gated e2e tests for every release, this is not necessary anymore.
/close

**Pull request closed without merging**
