### PR TITLE
reconciliation race protection during upgrade with OPERATE_ON_RELEASE_IMAGE envvar

### PR DESCRIPTION
**Pull request by sjenning**
**What this PR does / why we need it**:
This PR reverts https://github.com/openshift/hypershift/pull/963 and uses a simplier approach to upgrade race protection.

The CPO and HCCO now have an optional `OPERATE_ON_RELEASE_IMAGE` envvar.  If the envvar is specified, the operator will only reconcile if the value of the flag matches `releaseImage` on the HCP.  If the envvar is not provided, the operator will reconcile regardless of `releaseImage` (development environments).

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by relyt0925 — CHANGES_REQUESTED** [review]
looks good: going to run through upgrades on IBM Side before merging

**Comment by csrwng** [comment]
/lgtm
/hold
(for when @relyt0925 finishes his testing)

**Review by relyt0925 — APPROVED** [review]

**Comment by relyt0925** [comment]
/unhold

great work looks good

**Comment by sjenning** [comment]
Weird, `main` movement resulted in an unused import.  Fixed now.

**Pull request merged**
