### PR TITLE
OTA-1349: *: Propagate RetrievedUpdates from ClusterVersion up to HostedCluster

### PR DESCRIPTION
**Pull request by wking**
**What this PR does / why we need it**:

The pull propagates `RetrievedUpdates` from ClusterVersion up to HostedCluster

To make it easier for folks working at the management-cluster level to notice and address issues with update-recommendation retrieval.

Especially useful since de4bcbe35e (#3576) made `updateService` a configurable knob, because:

* Users might configure a broken `updateService`, and the new condition would tell them that it wasn't working.
* Users might install a 4.15 or earlier HostedCluster, where the HostedControlPlane controller (which is extracted from the HostedCluster's release image) was too old to have de4bcbe35e, so it doesn't propagate the configured `updateService`, and the cluster-version operator ends up using the default upstream update service.  That doesn't work in disconnected/restricted-network environments where `api.openshift.com` is unreachable.  The new condition would tell them that it wasn't working, and that the CVO was using the api.openshift.com service.  They'd be left on their own to realize that the `updateService` feature required a 4.16 or later HostedCluster release image.

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by wking** [comment]
[`failed to wait for importing imagestreamtags ... because of missing definition in the spec`][1] is an orthogonal CI flake.

/test e2e-aws

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws/1836210844564721664#1:build-log.txt%3A53

**Comment by wking** [comment]
[e2e-aws-4.17][1] [`TestCreateCluster` artifacts][2]:

```yaml
  - lastTransitionTime: "2024-09-18T01:45:13Z"
    message: Condition not found in the CVO.
    observedGeneration: 3
    reason: StatusUnknown
    status: Unknown
    type: ClusterVersionRetrievedUpdates
```

The HostedCluster doesn't set `spec.channel`, which means the cluster should not be attempting to retrieve update recommendations anyway.  I dunno if the test collects ClusterVersion YAML from the hosted Kube API.  So not all that much of a test, but :shrug:

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws-4-17/1836210844598276096
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws-4-17/1836210844598276096/artifacts/e2e-aws-4-17/hypershift-aws-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-srz6h/hypershift.openshift.io/hostedclusters/

**Comment by wking** [comment]
Ok, and in [e2e-aws][1], where the HostedControlPlane controller understands the piping, [`TestCreateCluster` artifacts][2]:

```yaml
  - lastTransitionTime: "2024-09-18T02:55:19Z"
    message: The update channel has not been configured.
    observedGeneration: 3
    reason: NoChannel
    status: "False"
    type: ClusterVersionRetrievedUpdates
```

So now we have examples of the new HyperShift operator code vs. both new (works) and old (`Condition not found in the CVO`) hosted cluster versions, and that all looks good to me.  It's not found in HostedControlPlane despite being in ClusterVersion, but probably not worth nit-picking the existing not-found string over.

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws/1836223840045240320
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws/1836223840045240320/artifacts/e2e-aws/hypershift-aws-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-q8mx9/hypershift.openshift.io/hostedclusters/

**Comment by wking** [comment]
[e2e-aws][1] [has][2]:

```yaml
  - lastTransitionTime: "2024-09-18T23:37:31Z"
    message: The update channel has not been configured.
    observedGeneration: 3
    reason: NoChannel
    status: "False"
    type: ClusterVersionRetrievedUpdates
```

and [e2e-aws-4.17][3] [has][4]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws-4-17/1836539839235756032/artifacts/e2e-aws-4-17/hypershift-aws-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-6lmhs/hypershift.openshift.io/hostedclusters/example-tjwjg.yaml | yaml2json | jq -r '.status.conditions[].type' | grep ClusterVersion | sort
ClusterVersionAvailable
ClusterVersionProgressing
ClusterVersionReleaseAccepted
ClusterVersionSucceeding
ClusterVersionUpgradeable
```

so fa5743e266573 is working as intended.


[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws/1836539839151869952
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws/1836539839151869952/artifacts/e2e-aws/hypershift-aws-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-qg7b9/hypershift.openshift.io/hostedclusters/example-rg7m6.yaml
[3]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws-4-17/1836539839235756032
[4]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/4744/pull-ci-openshift-hypershift-main-e2e-aws-4-17/1836539839235756032/artifacts/e2e-aws-4-17/hypershift-aws-run-e2e/artifacts/TestCreateCluster/namespaces/e2e-clusters-6lmhs/hypershift.openshift.io/hostedclusters/example-tjwjg.yaml

**Review by sjenning — APPROVED** [review]

**Comment by wking** [comment]
ah, possibly we were failing until openshift/cloud-provider-aws#95 merged.  Trying again now:

/retest-required

**Pull request merged**
