### PR TITLE
NO-JIRA: Fix the getting started page by adding export to BUCKET_NAME

### PR DESCRIPTION
**Pull request by marcbrown2024**
**What this PR does / why we need it**:
BUCKET_NAME is required to be exported to be accessed by the process that creates policy.json

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [x] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by bryan-cox** [comment]
Thanks @marcbrown2024 , did you run into this while using a Mac? I don't think this issue exists when following those instructions on Linux. It doesn't hurt to export it either way though.

**Comment by bryan-cox** [comment]
/retitle NO-JIRA: Fix the getting started page by adding export to BUCKET_NAME

**Comment by marcbrown2024** [comment]
> Thanks @marcbrown2024 , did you run into this while using a Mac? I don't think this issue exists when following those instructions on Linux. It doesn't hurt to export it either way though.

I was using linux, fedora to be specific.

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
