### PR TITLE
e2e: add AWS cluster create test

### PR DESCRIPTION
**Pull request by sjenning**
This PR re-adds the `TestClusterCreate` test in the e2e suite.

The original rationale for removing it was that it was a subset of `TestUpgradeControlPlane`.  However, this is not exactly true as `TestUpgradeControlPlane` _creates_ the cluster with the existing hypershift code and then _upgrades_ to the code under test. There is no test that ensures that the code under test can initially create a cluster.

Additionally we have some situations where we break upgrade compatibility against pre-release versions of OCP.  The work to move the CNO into the management cluster is an example.  Such a change will always fail the upgrade test, but should pass a create test like the one being reintroduced in this PR.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold

To wait for test result

**Comment by sjenning** [comment]
/test e2e-aws

post https://github.com/openshift/release/pull/27774 merge

**Review by alvaroaleman — APPROVED** [review]
/hold cancel

It is a presubmit now so we don't have to wait for e2e-aws-all

**Comment by sjenning** [comment]
Changed negative caching on the CI domain SOA record.  Once more!

/test e2e-aws

**Comment by alvaroaleman** [comment]
test is green, lets get this merged
/hold cancel

**Pull request merged**
