### PR TITLE
OCPBUGS-43698: dump: make ControlPlaneComponent's GKV optional

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

We now have a new list named `featureGatedResources` which will contain
the GVKs that live behind a feature gate (e.g. ControlPlaneComponent).
This list, combined with the previously tested `ocpResources`, will be
registering the GVKs that actually exist on the management cluster and
ignore the rest.

### CODE REVIEW

**Comment by EmilienM** [comment]
I checked the logs and it fixed the bug.
/hold cancel

**Comment by MaysaMacedo** [comment]
/test e2e-openstack

feel free to unhold if the error looks unrelated to you

**Pull request merged**
