### PR TITLE
[release-4.15] OCPBUGS-30862: Manual cherry pick 3685&3727 to release 4.15

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**
This is a manual  cherry-pick of https://github.com/openshift/hypershift/pull/3685 & https://github.com/openshift/hypershift/pull/3727

### CODE REVIEW

**Comment by Patryk-Stefanski** [comment]
https://github.com/openshift/hypershift/pull/3740

**Comment by muraee** [comment]
can you squash the commits please.

**Pull request merged**
