### PR TITLE
Set shutdown params to improve graceful shutdown

### PR DESCRIPTION
**Pull request by pcrentsil**
Added shutdown-send-retry-after and updated shutdown-delay-duration

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by relyt0925** [comment]
These parameters help in HA environments in ensuring no request failures on rollouts/restarts of API Server components. The components allow the APIServer to continue gracefully serving existing requests that it has received while shutting itself off for new requests for a period of time specified by shutdown-delay-duration.

**Review by alvaroaleman — COMMENTED** [review]
/retile: KAS: Set shutdown params to improve graceful shutdown

Please also update the commit with that title.

**Comment by pcrentsil** [comment]
> /retile: KAS: Set shutdown params to improve graceful shutdown
> 
> Please also update the commit with that title.

Updated!

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
