### PR TITLE
Validate pods running or completed in e2e tests

### PR DESCRIPTION
**Pull request by taragu**
Validate pods running or completed in e2e tests

### CODE REVIEW

**Comment by sjenning** [comment]
This could be a source of flakes if a component is in the process of rolling out a config change or something.

What is the motivation for this change?

**Comment by taragu** [comment]
@sjenning here's the context: (from https://issues.redhat.com/browse/HOSTEDCP-225)

[This](https://github.com/openshift/hypershift/pull/469/files) seems to fix an issue we didn't realise we were suffering. The ignition payload was not fetching the core MachineConfig because of the wrong labels.

That resulted in the static pod haproxy not running in the guest cluster. That resulted in multiple pods crashlooping.

We should validate the guest cluster is operative. E.g wait until all the pods are running or fail otherwise

**Comment by csrwng** [comment]
@taragu we can catch that problem with the current checks we have. The problem is we were testing the 4.8 control plane operator with the 4.8 hypershift operator. We should have been using the latest (main) hypershift operator instead. That's being fixed here: https://github.com/openshift/release/pull/22115

**Comment by enxebre** [comment]
>we can catch that problem with the current checks we have. 

Can we though? we are validating operators reports back successfully but we are not validating explicitly all pods are running/complete right? May be we can introduce this as a safety check that could help highlight subtle issues since the impact in the e2e total time should be none. WDYT?

**Comment by csrwng** [comment]
> Can we though?

Yes, in the case you pointed out above, the service-ca operator would never have reported available because the operator itself was failing to start. 

My concern with this additional check is that it could result in false positives and instability in CI due to transient pod states.

**Comment by ironcladlou** [comment]
>This seems to fix an issue we didn't realise we were suffering. The ignition payload was not fetching the core MachineConfig because of the wrong labels.

>That resulted in the static pod haproxy not running in the guest cluster. That resulted in multiple pods crashlooping.

>We should validate the guest cluster is operative. E.g wait until all the pods are running or fail otherwise

We do validate the guest cluster by relying on conditions on the HostedControlPlane which aggregate conditions/status of operators in the guest cluster.

I agree with @csrwng that a blind check of pods is undesirable. All control plane pods should be operated by some controller and their status surfaced through higher level abstraction (e.g. operator status). Reaching into the guest from this test and checking pods is something we've deliberately moved away from. We've progressively expanded status calculations in the control plane operator to assess control plane health and surface status through HCP/HostedCluster, and my preference would be to continue improving that without layering violations (e.g. coupling the e2e with an awareness of control plane implementation details in the form of specific pod or operator introspection).

In the specific cited bug (https://github.com/openshift/hypershift/pull/469/files), what operator status should have been reporting the crashing pod? If the control plane is unhealthy but the HostedControlPlane status doesn't reflect that, it sounds like a bug in either the control plane operator or a control plane component that needs fixed so that status is being reported correctly.

**Comment by enxebre** [comment]
>I agree with @csrwng that a blind check of pods is undesirable. All control plane pods should be operated by some controller and their status surfaced through higher level abstraction (e.g. operator status). Reaching into the guest from this test and checking pods is something we've deliberately moved away from. We've progressively expanded status calculations in the control plane operator to assess control plane health and surface status through HCP/HostedCluster, and my preference would be to continue improving that without layering violations (e.g. coupling the e2e with an awareness of control plane implementation details in the form of specific pod or operator introspection).
In the specific cited bug (https://github.com/openshift/hypershift/pull/469/files), what operator status should have been reporting the crashing pod? If the control plane is unhealthy but the HostedControlPlane status doesn't reflect that, it sounds like a bug in either the control plane operator or a control plane component that needs fixed so that status is being reported correctly.

@ironcladlou @csrwng Although I fundamentally agree the cases that I'm concern about are those that we can't think of ahead of time and only realise afterwards. Those that will break us silently and then will cause painful debugging following git history backwards. I like to have a suite of e2e tests product oriented by matching functional requirements and user stories. The most fundamental one is "As a consumer of Hypershift I want to be able to run workloads successfully in a guest cluster right after installing". Today that's not e2e validated.
Anyway we can always pick up the discussion if something pops up :).

**Comment by csrwng** [comment]
> The most fundamental one and the one with wider scope is "As a consumer of Hypershift I want to be able to run workloads successfully in a guest cluster right after installing". Today that's not e2e validated.

@enxebre totally agree with you there, but I think that's something we can validate by running the origin e2e conformance test suite against a hypershift cluster. It should be part of our MVP to be able to run those tests succesfully.

**Comment by alvaroaleman** [comment]
ref https://issues.redhat.com/browse/HOSTEDCP-225

**Pull request closed without merging**
