### PR TITLE
OSASINFRA-3539: Add ipam to cluster-api assets

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This commit adds ipam to cluster-api assets
and to the hypershift API scheme. This resource
is needed by openstackfloatingippool in the
cluster-api-provider-openstack.

### CODE REVIEW

**Comment by EmilienM** [comment]
/lgtm
Thanks

**Comment by bryan-cox** [comment]
nit: the commit message should use the imperative mood - see 4) [here for more details](https://hypershift-docs.netlify.app/contribute/#prior-to-submitting-a-pull-request)

**Comment by bryan-cox** [comment]
/retest

For konflux

**Pull request merged**
