### PR TITLE
Azure: Setup public DNS

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

So far, the Azure create command doesn't have any DNS-related options
implemented. This adds --base-domain flag for create cluster and create
infra, passes on the base-domain to the cluster and uses it to find the
 id of the zone that hosts the base domain, to then also pass that on.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by csrwng** [comment]
@alvaroaleman you may want to add a description to your commit (re: what/why), other than that lgtm

**Comment by alvaroaleman** [comment]
@csrwng updated

**Comment by alvaroaleman** [comment]
Ref https://issues.redhat.com/browse/HOSTEDCP-242

**Pull request merged**
