### PR TITLE
[release-4.13] HOSTEDCP-1003: Set AWS conditions only for AWS platform

### PR DESCRIPTION
**Pull request by muraee**
cherry-pick of https://github.com/openshift/hypershift/pull/2604

### CODE REVIEW

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by enxebre** [comment]
/approve
/hold
on kubevirt

**Comment by davidvossel** [comment]
/hold cancel

we only need TestCreateCluster to pass in the kubevirt lane for 4.13. The nodepool tests do not work for the kubevirt platform in 4.13, only 4.14+

```
--- PASS: TestCreateCluster (1302.52s)
    --- PASS: TestCreateCluster/EnsureNodeCountMatchesNodePoolReplicas (0.43s)
    --- PASS: TestCreateCluster/EnsureNoCrashingPods (0.21s)
    --- PASS: TestCreateCluster/EnsureNodeCommunication (0.72s)
    --- SKIP: TestCreateCluster/EnsureAllRoutesUseHCPRouter (0.00s)
    --- PASS: TestCreateCluster/NoticePreemptionOrFailedScheduling (0.22s)
    --- PASS: TestCreateCluster/EnsureNoPodsWithTooHighPriority (0.09s)
    --- PASS: TestCreateCluster/EnsureHCPContainersHaveResourceRequests (0.08s)
    --- PASS: TestCreateCluster/EnsureAllContainersHavePullPolicyIfNotPresent (0.08s)
    --- PASS: TestCreateCluster/PreTeardownClusterDump (190.00s)
    --- PASS: TestCreateCluster/DestroyCluster_1 (137.43s)
    --- PASS: TestCreateCluster/EnsureAPIBudget (0.83s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/control-plane-operator_read (0.25s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/control-plane-operator_mutate (0.07s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/control-plane-operator_no_404_deletes (0.07s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/hypershift-operator_read (0.07s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/hypershift-operator_mutate (0.07s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/hypershift-operator_no_404_deletes (0.07s)
    --- PASS: TestCreateCluster/DeleteTestNamespace (0.13s)
    --- PASS: TestCreateCluster/ValidateMetricsAreExposed (21.56s)
``

**Pull request merged**
