### PR TITLE
Change control-plane-operator to work with 4.9

### PR DESCRIPTION
**Pull request by sjenning**
Now that we have branched `release-4.8`, make `main` work with 4.9.

**NOTE** This makes the `control-plane-operator` in the `main` branch incompatible with 4.8.

@csrwng @ironcladlou @benluddy @timflannagan @bparees @derekwaynecarr

### CODE REVIEW

**Comment by ironcladlou** [comment]
Isn't the CI config for this PR's jobs still deploying 4.8 OCP payloads?

```
[36mINFO[0m[2021-09-15T21:22:02Z] Imported release 4.8.3 created at 2021-07-28 12:55:32 +0000 UTC with 135 images to tag release:latest-e2e-aws-pooled 
[36mINFO[0m[2021-09-15T21:22:02Z] Imported release 4.8.0-0.nightly-2021-09-15-114854 created at 2021-09-15 11:59:44 +0000 UTC with 135 images to tag release:hosted-ocp-latest 
[36mINFO[0m[2021-09-15T21:22:04Z] Imported release 4.8.0-0.nightly-2021-09-14-045441 created at 2021-09-14 05:00:00 +0000 UTC with 135 images to tag release:hosted-ocp-previous 
[
```

**Comment by enxebre** [comment]
can we enumerate in the PR desc the steps we plan to follow to make sure we cover the following goals on CI:
- PRs against main affecting Hypershift run jobs for 4.8/4.9 CPO + PR Hypershift code.
- PRs against main affecting CPO run jobs for any previous release of Hypershift that must support the targeted CPO version + PR CPO code.

**Comment by sjenning** [comment]
https://github.com/openshift/release/pull/21948 meregd. Retry e2e.
/test e2e-aws-pooled

**Comment by sjenning** [comment]
4.9 cluster pool created now
/test e2e-aws-pooled

**Comment by sjenning** [comment]
Still an issue with the HCCO approving CSRs.  Pushing a fix.

**Pull request merged**
