### PR TITLE
Enable Azure Multi

### PR DESCRIPTION
**Pull request by LiangquanLi930**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by bryan-cox** [comment]
@LiangquanLi930 - would you please rebase this PR?

**Comment by csrwng** [comment]
Given that we will not add a multiarch field to the API spec, closing this PR

/close

**Pull request closed without merging**
