### PR TITLE
[release-4.13] kubevirt: Block metadata server egress

### PR DESCRIPTION
**Pull request by qinqon**
This is a manual cherry-pick of:
- https://github.com/openshift/hypershift/pull/2399

### CODE REVIEW

**Comment by qinqon** [comment]
/hold

Checking kubevirt lane manually

**Comment by qinqon** [comment]
manual kubevirt lane test 
```
--- FAIL: TestCreateCluster (1108.30s)
    --- PASS: TestCreateCluster/EnsureNodeCountMatchesNodePoolReplicas (1.06s)
    --- PASS: TestCreateCluster/EnsureNoCrashingPods (0.56s)
    --- PASS: TestCreateCluster/EnsureNodeCommunication (0.94s)
    --- SKIP: TestCreateCluster/EnsureAllRoutesUseHCPRouter (0.00s)
    --- PASS: TestCreateCluster/NoticePreemptionOrFailedScheduling (0.58s)
    --- PASS: TestCreateCluster/EnsureNoPodsWithTooHighPriority (0.23s)
    --- PASS: TestCreateCluster/EnsureHCPContainersHaveResourceRequests (0.20s)
    --- PASS: TestCreateCluster/EnsureAllContainersHavePullPolicyIfNotPresent (0.20s)
    --- PASS: TestCreateCluster/PreTeardownClusterDump (0.00s)
    --- PASS: TestCreateCluster/DestroyCluster_1 (140.19s)
    --- FAIL: TestCreateCluster/EnsureAPIBudget (2.17s)
        --- FAIL: TestCreateCluster/EnsureAPIBudget/control-plane-operator_read (0.70s)
        --- FAIL: TestCreateCluster/EnsureAPIBudget/control-plane-operator_mutate (0.18s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/control-plane-operator_no_404_deletes (0.18s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/hypershift-operator_read (0.18s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/hypershift-operator_mutate (0.18s)
        --- PASS: TestCreateCluster/EnsureAPIBudget/hypershift-operator_no_404_deletes (0.18s)
    --- PASS: TestCreateCluster/DeleteTestNamespace (0.36s)

```

**Comment by davidvossel** [comment]
fixes: https://issues.redhat.com/browse/OCPBUGS-11737

**Comment by davidvossel** [comment]
requires https://github.com/openshift/release/pull/38459

**Pull request merged**
