### PR TITLE
[release-4.16] OCPBUGS-37302: fix(api): Nodepool CEL validation fix

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Supersedes https://github.com/openshift/hypershift/pull/4393

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by rtheis** [comment]
@hasueki how do we get the fix on main verified faster so we can proceed with this PR?

**Comment by rtheis** [comment]
@hasueki are we able to bypass the Red Hat Konflux check?

**Comment by bryan-cox** [comment]
/override "Red Hat Konflux / hypershift-release-mce-26-on-pull-request"

**Pull request merged**
