### PR TITLE
remove flags set by CI env var

### PR DESCRIPTION
**Pull request by sjenning**
Follow on to https://github.com/openshift/release/pull/39012

Remove magic flag setting when running in CI.  Workflow in o/r now explicitly sets these flags.

### CODE REVIEW

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by bryan-cox** [comment]
Do we need to remove these lines from the e2e's too?

**Comment by sjenning** [comment]
/override "Red Hat Trusted App Pipeline / hypershift-azjx-on-pull-request"

**Pull request merged**
