### PR TITLE
OCPBUGS-13547: Pass release image version to MCO bootstrap via --payload-version

### PR DESCRIPTION
**Pull request by JoelSpeed**
**What this PR does / why we need it**:

MCO recently introduced a new flag `--payload-version` that expects to take the payload release version as a value. This is currently inert but will be required once openshift/machine-config-operator#3688 is merged.
This was added to the installer in openshift/installer#7160.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by csrwng** [comment]
/approve

The mcoBootstrapScript is a codepath we no longer use, so we should eventually remove it.

**Comment by JoelSpeed** [comment]
Looks to me like the API server went down for a bit during this test, not sure if this is expected to pass or not, will retest
/test e2e-kubevirt-aws-ovn

**Comment by csrwng** [comment]
/lgtm
thx!

**Pull request merged**
