### PR TITLE
OCPBUGS-19381: Let NodePools skip min version when SkipReleaseImageValidation is in HC

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
cc @csrwng @andreadecorte

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by enxebre** [comment]
/override pull-ci-openshift-hypershift-main-e2e-kubevirt-aws-ovn

**Pull request merged**
