### PR TITLE
Use go 1.18 for CI builds

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by sjenning** [comment]
re: aos-devel email, sounds like the 1.18 build is still being tested and might have FIPS support disabled

**Comment by alvaroaleman** [comment]
> re: aos-devel email, sounds like the 1.18 build is still being tested and might have FIPS support disabled

True, but we are not testing with FIPS at all

**Pull request merged**
