### PR TITLE
HOSTEDCP-910: Enable pprof in hosted etcd

### PR DESCRIPTION
**Pull request by rsevilla87**
**What this PR does / why we need it**:

Enables pprof in hosted etcd, similar to self-managed or not-hypershift openshift deployments

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[HOSTEDCP-910](https://issues.redhat.com/browse/HOSTEDCP-910)

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
what's the impact on resource consumption from having this enabled ootb?

**Comment by rsevilla87** [comment]
> what's the impact on resource consumption from having this enabled ootb?

Enabling Pprof does not have any performance impact as long as any of the pprof endpoints are not requested. Some small performance impact is expected when requesting for example a CPU profile for a given time range. But as we're not targeting any kind of continuous profiling on HCP's etcd, the performance impact will be null.

This option is already enabled in classic ROSA, ARO and self-managed deployments, and as far as I can tell it's not impacting the application performance.

**Comment by rsevilla87** [comment]
@enxebre need a review here

**Pull request closed without merging**
