### PR TITLE
fix(oauth): Do not proxy IBM Cloud IAM endpoints

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Fixes: https://github.com/openshift/hypershift/pull/1522#issuecomment-1234973427

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by enxebre** [comment]
@hasueki Any reason for this to not be using https://github.com/openshift/hypershift/blob/cb7c55daf7f06d46eddbdbaa529c1593ace58640/konnectivity-socks5-proxy/main.go?

https://issues.redhat.com/browse/HOSTEDCP-568

**Pull request merged**
