### PR TITLE
Add new --featuregate-manifest to /usr/bin/cluster-config-operator render

### PR DESCRIPTION
**Pull request by enxebre**
CI is currently borken https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1653511338548269056/artifacts/e2e-aws-ovn/run-e2e/artifacts/TestCreateCluster_PreTeardownClusterDump/namespaces/e2e-clusters-glkxm-example-qmb9l/core/pods/logs/kube-apiserver-79b6c48d7-mzv44-init-bootstrap-previous.log.

This introduced a new command which is effectively required https://github.com/openshift/cluster-config-operator/pull/288

This introduced new status in featureGate CRD https://github.com/openshift/api/pull/1405

Here it was added to the installer github.com/openshift/installer/pull/6990

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I think you may also need `--rendered-manifest-files=/tmp/manifests` and a `--payload-version` flag too, does the script have any idea what payload version is being deployed?

**Comment by enxebre** [comment]
> I think you may also need --rendered-manifest-files=/tmp/manifests and a --payload-version flag too, does the script have any idea what payload version is being deployed?

Right now this is just shim to get the script happy, the feature gate config for the KAS i actually coming from the HC API and plumbed in here https://github.com/openshift/hypershift/blob/e7eb32f259b2a01e5bbdddf2fe963b82b331180f/control-plane-operator/controllers/hostedcontrolplane/kas/params.go#L445-L453

https://github.com/openshift/hypershift/blob/e7eb32f259b2a01e5bbdddf2fe963b82b331180f/control-plane-operator/controllers/hostedcontrolplane/kas/config.go#LL178C1-L178C1

By looking at the render cluster-config render command I think this should be enough, let's see what it breaks via CI otherwise.

**Comment by enxebre** [comment]
```
F0503 11:00:52.315509      10 render.go:53] problem with featuregate manifests: cannot return FeatureGate without rendered manifests
cp: cannot stat '/tmp/output/manifests/*': No such file or directory
```

updated to include `--rendered-manifest-files`

**Pull request merged**
