### PR TITLE
OCPBUGS-26977: Required RBAC for network-node-identity is not created when hosted cluster networkType is set to Other.

### PR DESCRIPTION
**Pull request by mvazquezc**
**What this PR does / why we need it**:
Fixes #OCPBUGS-26977

**Checklist**
- [X] Subject and description added to both, commit and PR.
- [X] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [X] This change includes unit tests.

### CODE REVIEW

**Comment by jparrill** [comment]
We've been working together into the PR review through a huddle. Already changes done.

/lgtm

**Comment by bryan-cox** [comment]
Removing previous hold since it was placed by failing tests
/Unhold

**Pull request merged**
