### PR TITLE
Add agent platform to docs

### PR DESCRIPTION
**Pull request by avishayt**
**What this PR does / why we need it**:
Add documentation for using the agent platform

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[MGMT-8469](https://issues.redhat.com/browse/MGMT-8469)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [x] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
Please update the mkdocs.yml file to ensure the new file is rendered.
I think this should instead belong to getting-started/Agent-platform?

**Comment by avishayt** [comment]
> I think this should instead belong to getting-started/Agent-platform?

Do you mean that it should be a section in getting-started.md?

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by enxebre** [comment]
>Do you mean that it should be a section in getting-started.md?

Yes, I think I'd rather have getting-started-aws, getting-started-agent and then getting-started-kubevirt https://github.com/openshift/hypershift/pull/985

cc @csrwng @alvaroaleman @ironcladlou @sjenning

**Comment by sjenning** [comment]
I do see `HostedCluster` and `NodePool` create/manage/destroy being sufficiently different between the platforms that they justify per-platform docs on this.

In fact, I was going to write one up for bare-metal.

**Pull request merged**
