### PR TITLE
Dump KubeVirt pod logs

### PR DESCRIPTION
**Pull request by nunnatsa**
**What this PR does / why we need it**:
Add the log of KubeVirt pods, to the dump result.

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by nunnatsa** [comment]
./test e2e-aws

**Pull request merged**
