### PR TITLE
WIP: Add missing etcd operator config

### PR DESCRIPTION
**Pull request by Evan-Reilly**
**What this PR does / why we need it**:

These changes add the missing etcd operator config (see https://github.ibm.com/alchemy-containers/armada-update/issues/5529) which fixes the `[ocp-conformance][test failure] The server doesn't have a resource type "etcds"` OCP conformance test in ROKS v4.15.  A similar change was done for the ibm-roks-toolkit for ROKS v4.14 https://github.com/openshift/ibm-roks-toolkit/pull/884/files.  These changes, however, should only be cherry-picked to ROKS v4.15.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@sjenning this looks like a bug in the conformance suite.  there is no reason this should be required when hosted.

**Comment by rtheis** [comment]
/hold per https://github.com/openshift/hypershift/pull/3807#issuecomment-2037349996

@derekwaynecarr thanks for letting us know.  @Evan-Reilly let's discuss.

**Comment by rtheis** [comment]
Conformance test is `[sig-cli] oc explain should contain proper spec+status for CRDs [Suite:openshift/conformance/parallel]`

**Comment by Evan-Reilly** [comment]
@sjenning @derekwaynecarr Is there an update on the status of this? When could we expect an update to the conformance suite?

**Comment by stevekuznetsov** [comment]
/retitle WIP: Add missing etcd operator config

**Comment by rtheis** [comment]
@sjenning @derekwaynecarr do you have any updates to share?

**Comment by csrwng** [comment]
@rtheis @Evan-Reilly The fix needs to go into the conformance test suite. Basically change [this function](https://github.com/openshift/origin/blob/eb965ec945e7ffc1f1b09c63c3c9a7de5321d833/test/extended/cli/explain.go#L501) to omit the etcds resource when the cluster is HyperShift. Can you submit a PR for that?

I am closing this PR, since the change doesn't belong here.
/close

**Comment by rtheis** [comment]
@csrwng yes, we can handle that.

**Comment by Evan-Reilly** [comment]
@csrwng @rtheis https://github.com/openshift/origin/pull/29114

**Pull request closed without merging**
