### PR TITLE
HOSTEDCP-1921: Remove unused CAPZ CRDs from HyperShift install

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it**:
Remove unused CAPZ managed related CRDs from the HyperShift install since those are not used in HyperShift.

**Which issue(s) this PR fixes**:
Fixes [HOSTEDCP-1921](https://issues.redhat.com/browse/HOSTEDCP-1921)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by bryan-cox** [comment]
e2e-aks is legitimately failing. I'll take a look into it today.

**Comment by bryan-cox** [comment]
Looks like the error is related to this
```
E0828 10:05:27.972237       1 kind.go:63] "if kind is a CRD, it should be installed before calling Start" err="failed to get restmapping: no matches for kind \"AzureManagedControlPlane\" in group \"infrastructure.cluster.x-k8s.io\"" logger="controller-runtime.source.EventHandler" kind="AzureManagedControlPlane.infrastructure.cluster.x-k8s.io"
```

**Comment by muraee** [comment]
looks like we need to turn off `MachinePool` feature gate to deactivate those controllers.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/main.go#L427

**Comment by bryan-cox** [comment]
> looks like we need to turn off `MachinePool` feature gate to deactivate those controllers. https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/main.go#L427

Looks like we already turn that off - https://github.com/openshift/hypershift/blob/6800721cc24088f8bc924b46b2d9ed438ad4da57/hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go#L93

**Comment by bryan-cox** [comment]
Moving this PR back to draft. This PR will be blocked for the moment. CAPZ is still registering the webhooks related to the CRDs even if the featuregate is disabled.

**Comment by bryan-cox** [comment]
This is blocked from further progress until https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5099 is merged and HyperShift is updated to use the new CAPZ version including the fix.

**Comment by bryan-cox** [comment]
/close
Will reopen this PR when we can

**Pull request closed without merging**
