### PR TITLE
Fast forward 'release-4.12' branch to 'main'

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
Merges main to release-4.12 branch

### CODE REVIEW

**Comment by enxebre** [comment]
>Error: failed to create infra: cannot create NAT gateway: NatGatewayLimitExceeded: Performing this operation would exceed the limit of 80 NAT gateways
	status code: 400, request id: f3628857-f1ba-4da6-8da4-913155f8cb40

/test e2e-aws

**Comment by csrwng** [comment]
/hold
Will test manually and override e2e-aws if the only test failing is pod restarts on the UpgradeControlPlane test

**Comment by csrwng** [comment]
/hold cancel 
Found the cause of the the recreating pods to be controllers/operators running on both the hosted cluster and control plane side. Fix PR here: https://github.com/openshift/hypershift/pull/1946

**Pull request merged**
