### PR TITLE
OCPBUGS-25897: hcco: use manual mode for CCO

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by huangmingxia** [comment]
Based on the discussion in [Slack](https://redhat-internal.slack.com/archives/C04KRSVAZ37/p1704352959978509) , QE conducted pre-merge testing.  Now, working as expected. Here are the test results:
 
1. Install a management cluster with STS.
```
 [hmx@fedora CCO-386]$ oc get hc -A
NAMESPACE   NAME                  VERSION                                                   KUBECONFIG                             PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
clusters    hypershift-ci-12111   4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   hypershift-ci-12111-admin-kubeconfig   Completed   True        False         The hosted control plane is available

[hmx@fedora CCO-386]$  oc get nodepool -n clusters
NAME                             CLUSTER               DESIRED NODES   CURRENT NODES   AUTOSCALING   AUTOREPAIR   VERSION                                                   UPDATINGVERSION   UPDATINGCONFIG   MESSAGE
hypershift-ci-12111-us-east-2a   hypershift-ci-12111   1               1               False         False        4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest                                      
hypershift-ci-12111-us-east-2b   hypershift-ci-12111   1               1               False         False        4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest                                      
hypershift-ci-12111-us-east-2c   hypershift-ci-12111   1               1               False         False        4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest 

 [hmx@fedora CCO-386]$ oc get cloudcredential cluster -o jsonpath --template '{ .spec.credentialsMode  }' 
Manual
```
2. Install a management cluster with default mode(mint).
```
 hmx@fedora ~]$ oc get hc -A
NAMESPACE   NAME                 VERSION                                                   KUBECONFIG                            PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
clusters    hypershift-ci-8994   4.15.0-0.ci.test-2024-01-08-012538-ci-ln-pi7itmb-latest   hypershift-ci-8994-admin-kubeconfig   Completed   True        False         The hosted control plane is available

[hmx@fedora ~]$ oc get cloudcredential cluster -n clusters-hypershift-ci-8994 -o yaml
apiVersion: operator.openshift.io/v1
kind: CloudCredential
metadata:
  creationTimestamp: "2024-01-08T01:40:13Z"
  generation: 1
  name: cluster
  resourceVersion: "513"
  uid: cd355172-c2c3-49d8-b31c-3f47ead6480e
spec:
  credentialsMode: ""
  logLevel: Normal
  operatorLogLevel: Normal
```

3. It should be manual mode on Hosted Cluster no matter what the credentialsMode of Management Cluster is.
```
Management clusters are in STS mode and the credentialsMode for hosted clusters is:
$ oc get cloudcredential cluster -o jsonpath --template '{ .spec.credentialsMode }'
Manual

Management clusters are in Mint mode and the credentialsMode for hosted clusters is:
$ oc get cloudcredential cluster -o jsonpath --template '{ .spec.credentialsMode }'
Manual
```

4. The CCO is expected to run on the control plane NS, not on the customer's worker nodes, and not be visible to the customer.

CCO operator is expected to run on the HyperShift control plane namespace. 
```
[hmx@fedora CCO-386]$ oc get pod -n clusters-hypershift-ci-12111 -l app=cloud-credential-operator
NAME                                         READY   STATUS    RESTARTS   AGE
cloud-credential-operator-698b777bcf-v5qnt   1/1     Running   0          16m
```

CCO operator is not expected to run on the HyperShift hosted cluster.
```
$ oc get co
NAME                                       VERSION                                                   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
console                                    4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      9m5s    
csi-snapshot-controller                    4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
dns                                        4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      10m     
image-registry                             4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      10m     
ingress                                    4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      9m41s   
insights                                   4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      10m     
kube-apiserver                             4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
kube-controller-manager                    4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
kube-scheduler                             4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
kube-storage-version-migrator              4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      10m     
monitoring                                 4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      7m49s   
network                                    4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
node-tuning                                4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      12m     
openshift-apiserver                        4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
openshift-controller-manager               4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
openshift-samples                          4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      9m59s   
operator-lifecycle-manager                 4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
operator-lifecycle-manager-catalog         4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
operator-lifecycle-manager-packageserver   4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      16m     
service-ca                                 4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      10m     
storage                                    4.15.0-0.ci.test-2024-01-05-145018-ci-ln-dts7i1b-latest   True        False         False      11m     

$ oc get all -n openshift-cloud-credential-operator
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/cco-metrics   ClusterIP   172.31.104.192   <none>        8443/TCP   17m
```

5.  If CCO has the logic to generate secrets on HyperShift Hosted Cluster, following conditions need to be met:

- CloudCredential.spec.CredentialsMode is set to Manual.
- CloudCredential.spec.ManagementState is set to Managed.
- Auth.serviceAccountIssuer is not empty.

HyperShift control plane(The states are consistent with management cluster):

Management clusters are in STS mode:
```
$ oc get authentication cluster -n clusters-hypershift-ci-26499 -o jsonpath --template '{ .spec.serviceAccountIssuer }'
https://mihuang106-13424-oidc.s3.us-east-2.amazonaws.com

$ oc get cloudcredential cluster -n clusters-hypershift-ci-26499 -o json
{
    "apiVersion": "operator.openshift.io/v1",
    "kind": "CloudCredential",
    "metadata": {
        "creationTimestamp": "2024-01-05T16:17:40Z",
        "generation": 1,
        "name": "cluster",
        "resourceVersion": "505",
        "uid": "04e6a5d9-4296-456a-a841-9e7380f61432"
    },
    "spec": {
        "credentialsMode": "Manual",
        "logLevel": "Normal",
        "operatorLogLevel": "Normal"
    }
}

```
Management clusters are in Mint mode:
```
$ oc get authentication cluster -n clusters-hypershift-ci-8994 -o yaml
apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-01-08T01:40:26Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 83c0a07d-e7cc-4db0-88c1-7771669e3f62
  resourceVersion: "21160"
  uid: aa4c2a03-8dec-46dc-8048-670c00c1bf39
spec:
  oauthMetadata:
    name: ""
  serviceAccountIssuer: ""
  type: ""
  webhookTokenAuthenticator:
    kubeConfig:
      name: webhook-authentication-integrated-oauth
status:
  integratedOAuthMetadata:
    name: oauth-openshift

$ oc get cloudcredential cluster -n clusters-hypershift-ci-8994 -o yaml
apiVersion: operator.openshift.io/v1
kind: CloudCredential
metadata:
  creationTimestamp: "2024-01-08T01:40:13Z"
  generation: 1
  name: cluster
  resourceVersion: "513"
  uid: cd355172-c2c3-49d8-b31c-3f47ead6480e
spec:
  credentialsMode: ""
  logLevel: Normal
  operatorLogLevel: Normal
```

Hosted Cluster：
(Management clusters in STS mode and management clusters in Mint mode have the same result)
```
$  ./bin/hypershift create kubeconfig > hostedcluster.kubeconfig

$ oc get authentication cluster -o jsonpath --template '{ .spec.serviceAccountIssuer }' 
https://aos-hypershift-ci-oidc-12111.s3.us-east-2.amazonaws.com/hypershift-ci-12111

$ oc get cloudcredential cluster -o jsonpath --template '{ .spec.managementState }' 
Managed

$  oc get cloudcredential cluster -o jsonpath --template '{ .spec.credentialsMode  }' 
Manual

$ oc get cloudcredential cluster -o json
{
    "apiVersion": "operator.openshift.io/v1",
    "kind": "CloudCredential",
    "metadata": {
        "creationTimestamp": "2024-01-05T16:48:09Z",
        "generation": 1,
        "labels": {
            "hypershift.openshift.io/managed": "true"
        },
        "name": "cluster",
        "resourceVersion": "1539",
        "uid": "7a9e40f3-3097-4af8-9d30-5eda846e098d"
    },
    "spec": {
        "credentialsMode": "Manual",
        "logLevel": "Normal",
        "managementState": "Managed",
        "observedConfig": null,
        "operatorLogLevel": "Normal",
        "unsupportedConfigOverrides": null
    }
}
```
6. Creates CredentialsRequest including the spec.providerSpec.stsIAMRoleARN string on Hosted Cluster.
Cloud Credential Operator populates Secret based on CredentialsRequest.

```
$ cat CredentialsRequest.yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: test-mihuang
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    stsIAMRoleARN: arn:aws:iam::269733383066:role/newstscluster-openshift-logging-role-name
    statementEntries:
    - action:
      - ec2:CreateTags
      effect: Allow
      resource: '*'
  secretRef:
    name: test-secret
    namespace: default
  serviceAccountNames:
  - default

$ oc apply -f CredentialsRequest.yaml

[hmx@fedora hypershift-util]$ oc get secret
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-fptkc    kubernetes.io/dockercfg               1      28m
builder-token-tgmrm        kubernetes.io/service-account-token   4      28m
default-dockercfg-lthj9    kubernetes.io/dockercfg               1      28m
default-token-x9tdm        kubernetes.io/service-account-token   4      28m
deployer-dockercfg-lhpgd   kubernetes.io/dockercfg               1      28m
deployer-token-h24rk       kubernetes.io/service-account-token   4      28m
test-mihuang               Opaque                                1      3s

[hmx@fedora hypershift-util]$ oc get CredentialsRequest -n openshift-cloud-credential-operator
NAME                                                  AGE
openshift-cloud-network-config-controller-aws         29m
openshift-cloud-network-config-controller-azure       29m
openshift-cloud-network-config-controller-gcp         29m
openshift-cloud-network-config-controller-openstack   29m
openshift-image-registry                              28m
openshift-image-registry-alibaba                      29m
openshift-image-registry-azure                        29m
openshift-image-registry-gcs                          29m
openshift-image-registry-ibmcos                       29m
openshift-image-registry-ibmcos-powervs               29m
openshift-image-registry-openstack                    29m
openshift-ingress                                     29m
openshift-ingress-azure                               29m
openshift-ingress-gcp                                 29m
test-mihuang                                          21s

[hmx@fedora hypershift-util]$ oc get CredentialsRequest -n openshift-cloud-credential-operator test-mihuang -o yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cloudcredential.openshift.io/v1","kind":"CredentialsRequest","metadata":{"annotations":{},"name":"test-mihuang","namespace":"openshift-cloud-credential-operator"},"spec":{"providerSpec":{"apiVersion":"cloudcredential.openshift.io/v1","kind":"AWSProviderSpec","statementEntries":[{"action":["ec2:CreateTags"],"effect":"Allow","resource":"*"}],"stsIAMRoleARN":"arn:aws:iam::269733383066:role/newstscluster-openshift-logging-role-name"},"secretRef":{"name":"test-mihuang","namespace":"default"},"serviceAccountNames":["default"]}}
  creationTimestamp: "2024-01-05T17:16:45Z"
  finalizers:
  - cloudcredential.openshift.io/deprovision
  generation: 1
  name: test-mihuang
  namespace: openshift-cloud-credential-operator
  resourceVersion: "32246"
  uid: 05151e98-e5df-40c6-9b10-6e5e1942505a
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - ec2:CreateTags
      effect: Allow
      resource: '*'
    stsIAMRoleARN: arn:aws:iam::269733383066:role/newstscluster-openshift-logging-role-name
  secretRef:
    name: test-mihuang
    namespace: default
  serviceAccountNames:
  - default
status:
  lastSyncGeneration: 1
  lastSyncTimestamp: "2024-01-05T17:17:32Z"
  provisioned: true
```

7. Creates CredentialsRequest w/o the spec.providerSpec.stsIAMRoleARN string on Hosted Cluster.
Cloud Credential Operator **can not populates Secret** based on CredentialsRequest.

```
$ cat CredentialsRequest.yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: test-mihuang
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - ec2:CreateTags
      effect: Allow
      resource: '*'
  secretRef:
    name: test-mihuang
    namespace: default
  serviceAccountNames:
  - default

$ oc apply -f CredentialsRequest.yaml
$ oc get secret
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-kdmrh    kubernetes.io/dockercfg               1      5h54m
builder-token-6q6rz        kubernetes.io/service-account-token   4      5h54m
default-dockercfg-slx64    kubernetes.io/dockercfg               1      5h54m
default-token-ln4dc        kubernetes.io/service-account-token   4      5h54m
deployer-dockercfg-c45ts   kubernetes.io/dockercfg               1      5h54m
deployer-token-qwhws       kubernetes.io/service-account-token   4      5h54m

[hmx@fedora hypershift-util]$ oc get CredentialsRequest -n openshift-cloud-credential-operator test-mihuang -o yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cloudcredential.openshift.io/v1","kind":"CredentialsRequest","metadata":{"annotations":{},"name":"test-mihuang","namespace":"openshift-cloud-credential-operator"},"spec":{"providerSpec":{"apiVersion":"cloudcredential.openshift.io/v1","kind":"AWSProviderSpec","statementEntries":[{"action":["ec2:CreateTags"],"effect":"Allow","resource":"*"}]},"secretRef":{"name":"test-mihuang","namespace":"default"},"serviceAccountNames":["default"]}}
  creationTimestamp: "2024-01-09T09:18:14Z"
  finalizers:
  - cloudcredential.openshift.io/deprovision
  generation: 1
  name: test-mihuang
  namespace: openshift-cloud-credential-operator
  resourceVersion: "142752"
  uid: a94c09c2-92a1-40a1-ab0c-10549b5f4df2
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - ec2:CreateTags
      effect: Allow
      resource: '*'
  secretRef:
    name: test-mihuang
    namespace: default
  serviceAccountNames:
  - default
status:
  conditions:
  - lastProbeTime: "2024-01-09T09:18:17Z"
    lastTransitionTime: "2024-01-09T09:18:17Z"
    message: 'failed to grant creds: an empty awsSTSIAMRoleARN was found so no Secret
      was created'
    reason: CredentialsProvisionFailure
    status: "True"
    type: CredentialsProvisionFailure
  lastSyncGeneration: 0
  lastSyncTimestamp: "2024-01-09T09:18:45Z"
  provisioned: false
```

**Pull request merged**
