### PR TITLE
Revert "Merge pull request #2770 from dharaneeshvrd/upgrade-capi-ibmcloud

### PR DESCRIPTION
**Pull request by sjenning**
https://github.com/openshift/hypershift/pull/2770 took out CI with `installer` failing in the root CI cluster

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1676933960199835648/artifacts/e2e-aws-ovn/dump-management-cluster/artifacts/namespaces/hypershift/core/pods/logs/installer-59cfd4cff9-9xdgj-installer-previous.log

### CODE REVIEW

**Comment by enxebre** [comment]
@dharaneeshvrd 
This is because we didn't account for transitions from existing HC/HOs.
See https://github.com/openshift/hypershift/pull/2000
https://github.com/openshift/hypershift/blob/main/api/v1beta1/capi_types.go#L5-L6
Also I'm not sure how this could work at all given you are pointing to v1 here https://github.com/openshift/hypershift/blob/main/cmd/install/assets/assets.go#L37-L41

If you don't want any kind of backward compatibility the hypershift install would need to account for removing existing CRDs first so apply command stop complaining about the stored version.

**Comment by dharaneeshvrd** [comment]
@enxebre 
Apologies for the inconvenience caused and thanks for the input.
I have reworked on this and created a PR here https://github.com/openshift/hypershift/pull/2831
Tested the upgrade scenarios works fine.

Please review this PR

**Pull request merged**
