### PR TITLE
OCPBUGS-13639: Cherry pick aws endpoint sg

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:
Cherry-picks https://github.com/openshift/hypershift/pull/2574 and https://github.com/openshift/hypershift/pull/2529
in one go to avoid chance to face the nil deref.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by heliubj18** [comment]
@enxebre I see they are pushing the 4.12 fix now. I tested 4.13/4.14 and it passed. I think we could continue to merge this PR and then I could test it on OCP 4.12 nightly. Thank!

**Pull request merged**
