### PR TITLE
OCPBUGS-32760: Request serving scheduler: omit deleting nodes

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
Avoid taking deleting nodes into consideration when making scheduling decisions.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[OCPBUGS-32760](https://issues.redhat.com/browse/OCPBUGS-32760)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by csrwng** [comment]
/override "Red Hat Konflux / hypershift-operator-main-on-pull-request"

**Comment by bryan-cox** [comment]
/retest

For konflux

**Pull request merged**
