### PR TITLE
[release-4.12] Bug HOSTEDCP-604: Don't store machine payload in token secret for replace node pools (#1873)

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Manual cherry-pick of https://github.com/openshift/hypershift/pull/1873

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
this is breaking https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_hypershift/1881/pull-ci-openshift-hypershift-release-4.12-verify/1593738302819667968/build-log.txt

**Comment by hasueki** [comment]
Thanks @enxebre, I must've messed up something in the rebase. Will update.

**Comment by csrwng** [comment]
@hasueki we are planning to do a fast-forward of 4.12 to main shortly, which should include this PR as well

**Pull request closed without merging**
