### PR TITLE
HOSTEDCP-1003: Set AWS conditions only for AWS platform

### PR DESCRIPTION
**Pull request by muraee**
**What this PR does / why we need it**:
This makes sure AWS specific conditions are only set if platform is AWS

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[HOSTEDCP-1003](https://issues.redhat.com/browse/HOSTEDCP-1003)

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
/approve
ptal @davidvossel

**Comment by davidvossel** [comment]
/test e2e-kubevirt-aws-ovn

kubevirt failed the nodepool condition test due to this. `nodepool_test.go:255: Failed to validate NodePool conditions in 0s: unknown condition ValidArchPlatform`

however, I merged a fix yesterday for this here, https://github.com/openshift/hypershift/commit/3153774c369c23851b20d1c7b341f7cdd0832932 

so this should hopefully pass if we re-kick the test.

**Comment by davidvossel** [comment]
/lgtm cancel

actually, the failure is related to this pr
```nodepool_test.go:255: Failed to validate NodePool conditions in 0s: unknown condition ValidArchPlatform```

**Comment by muraee** [comment]
@davidvossel I added an exception/check for the `ValidArchPlatform` condition

**Comment by davidvossel** [comment]
/test e2e-kubevirt-aws-ovn

I see the `TestNTOMachineConfigGetsRolledOut` test is failing for kubevirt. I believe this test is flaky though. I'm going to give it another try. I'm also investigating this locally on my cluster to see why the test fails.

**Comment by davidvossel** [comment]
/test e2e-kubevirt-aws-ovn

this time the HC failed to roll out

**Pull request merged**
