### PR TITLE
fix(nto): Disable service account token automount

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:
Components that do not need access to the mgmt cluster should not automount service account tokens.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
@hasueki nto consumes from management cluster ns https://github.com/openshift/enhancements/blob/master/enhancements/hypershift/node-tuning.md#summary 
cc @dagrayvid

**Comment by hasueki** [comment]
Aha ok, thank you for the pointer there @enxebre. So it looks like NTO simply needs ConfigMap access in the control plane namespace, is there anything else? And if so, can we create separate a ServiceAccount/RoleBinding/Role for NTO?

**Pull request closed without merging**
