### PR TITLE
OCPBUGS-19516: Upgrade agent APIs to v1beta1

### PR DESCRIPTION
**Pull request by CrystalChun**
**What this PR does / why we need it**:
Cluster-api-provider Agent has updated its APIs to v1beta1 from v1alpha1, so hypershift will need to use these new versions.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes [OCPBUGS-19516](https://issues.redhat.com//browse/OCPBUGS-19516)
[MGMT-14838](https://issues.redhat.com/browse/MGMT-14838)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

/cc @eranco74 @avishayt

### CODE REVIEW

**Comment by eranco74** [comment]
Hmmm, we still can't test the agent platform in presubmit?

**Comment by CrystalChun** [comment]
> Hmmm, we still can't test the agent platform in presubmit?

@LiangquanLi930 did you happen to add CI tests for agent platform?

**Comment by eranco74** [comment]
@csrwng please approve

**Comment by CrystalChun** [comment]
/retitle OCPBUGS-19516: Upgrade agent APIs to v1beta1

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Comment by enxebre** [comment]
@CrystalChun you'd need to update https://github.com/openshift/hypershift/blob/45e61f9497725664e12355ace0edf149ac05702a/cmd/install/assets/assets.go#L46-L48

Also have you test transitioning towards this in existing clusters?

**Comment by CrystalChun** [comment]
> @CrystalChun you'd need to update
> 
> https://github.com/openshift/hypershift/blob/45e61f9497725664e12355ace0edf149ac05702a/cmd/install/assets/assets.go#L46-L48
> 

Thank you for catching that! Will open a PR to fix that soon. 

> Also have you test transitioning towards this in existing clusters?

I haven't. Does this mean installing clusters using v1alpha1 then reinstalling hypershift or deploying the new capi agent provider that uses the new version?

**Pull request merged**
