### PR TITLE
OCPBUGS-32255: Remove kube-scheduler readiness probe

### PR DESCRIPTION
**Pull request by jonesbr17**
**What this PR does / why we need it**:
This container doesn't have an associated service, so a readiness probe doesn't make sense. It can be removed.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #https://issues.redhat.com/browse/OCPBUGS-32255

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by csrwng** [comment]
/override "Red Hat Konflux / hypershift-operator-main-on-pull-request"

**Comment by rtheis** [comment]
@jonesbr17 looks like you need to do a manual cherry-pick.

**Comment by enxebre** [comment]
Hi @jonesbr17, I'm curious was the readiness probe causing any issue?

**Pull request merged**
