### PR TITLE
OCPBUGS-38042:consider non extrenal-dns hc.services during azure hc validation

### PR DESCRIPTION
**Pull request by Patryk-Stefanski**
**What this PR does / why we need it**: the current validation prevents us from creating azure clusters without external DNS, this is blocking azure e2e from creating mgmt clusters because we use type loadbalancer for apiserver service when externalDNS is not specified, example of [failure](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4331/pull-ci-openshift-hypershift-main-e2e-azure/1820739851645882368) 

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # [OCPBUGS-38042](https://issues.redhat.com/browse/OCPBUGS-38042)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by csrwng** [comment]
Is this expected? (from e2e-azure failure)
```
2024-08-08T11:15:53Z	ERROR	Failed to create cluster	{"error": "failed to apply object \"clusters/9faf1537614023436235-mgmt\": HostedCluster.hypershift.openshift.io \"9faf1537614023436235-mgmt\" is invalid: [spec: Invalid value: \"object\": Azure platform requires APIServer Route service with a hostname to be defined, spec: Invalid value: \"object\": no such key: route evaluating rule: Azure platform requires OAuthServer Route service with a hostname to be defined, spec: Invalid value: \"object\": no such key: route evaluating rule: Azure platform requires Konnectivity Route service with a hostname to be defined, spec: Invalid value: \"object\": no such key: route evaluating rule: Azure platform requires Ignition Route service with a hostname to be defined]"}
```

**Comment by Patryk-Stefanski** [comment]
> Is this expected? (from e2e-azure failure)
> 
> ```
> 2024-08-08T11:15:53Z	ERROR	Failed to create cluster	{"error": "failed to apply object \"clusters/9faf1537614023436235-mgmt\": HostedCluster.hypershift.openshift.io \"9faf1537614023436235-mgmt\" is invalid: [spec: Invalid value: \"object\": Azure platform requires APIServer Route service with a hostname to be defined, spec: Invalid value: \"object\": no such key: route evaluating rule: Azure platform requires OAuthServer Route service with a hostname to be defined, spec: Invalid value: \"object\": no such key: route evaluating rule: Azure platform requires Konnectivity Route service with a hostname to be defined, spec: Invalid value: \"object\": no such key: route evaluating rule: Azure platform requires Ignition Route service with a hostname to be defined]"}
> ```

Yes, this is the issue that this pr should fix. The reason this test fails is because it uses the HO from main to create the mgmt cluster.

**Comment by Patryk-Stefanski** [comment]
/close 
atm we only allow for Azure clusters with external-dns

**Pull request closed without merging**
