### PR TITLE
OCPBUGS-35341: [release-4.16] Fixed ValidReleaseInfo condition

### PR DESCRIPTION
**Pull request by muraee**
**What this PR does / why we need it**:
backport of https://github.com/openshift/hypershift/pull/4129

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by jparrill** [comment]
@muraee As the cloned one has a dependant PR (https://github.com/openshift/hypershift/pull/4164) this dependant PR will be backported too?

**Comment by muraee** [comment]
@jparrill the condition show tell us if the sdk image is also removed in 4.16. then we should backport that PR.

**Pull request merged**
