### PR TITLE
feat(cpo): Support disable profiling annotation

### LINKED ISSUE #1438: Support disabling of go profiling for control plane components
We should disable go profiling for `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler` to follow security best practices highlighted in [CIS benchmark for Kubernetes](https://www.cisecurity.org/benchmark/kubernetes) and [this Red Hat blog](https://cloud.redhat.com/blog/12-kubernetes-configuration-best-practices). It would be a matter of setting `--profiling=false` on these containers.

For IBM Cloud, we need to make sure profiling is disabled to meet requirements highlighted in https://cloud.ibm.com/docs/openshift?topic=openshift-cis-benchmark-410

### PR DESCRIPTION
**Pull request by a-dsouza**
**What this PR does / why we need it**: Add annotation to support disabling profiling for control plane components. 

**Which issue(s) this PR fixes** 
Fixes #1438

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [x] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by a-dsouza** [comment]
If needed, I can implement unit tests after review.

**Review by csrwng — COMMENTED** [review]
Looks good to me, just a minor nit

**Pull request merged**
