### PR TITLE
Add release image validation for NodePools

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:
Add release image validation for NodePools:
- Move existing HC release image validation into support/ package.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
ref https://issues.redhat.com/browse/HOSTEDCP-543

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [x] This change includes unit tests.

### CODE REVIEW

**Comment by csrwng** [comment]
@enxebre I think this is good, but for nodepools we can't just validate the release on its own. We need to validate it in relation to the HC version. My initial thought is that we should not allow creating a new nodepool to anything other than the HC release version. And when upgrading a nodepool we should only be able to upgrade it to the current HC version.

**Comment by enxebre** [comment]
> @enxebre I think this is good, but for nodepools we can't just validate the release on its own. We need to validate it in relation to the HC version. My initial thought is that we should not allow creating a new nodepool to anything other than the HC release version. And when upgrading a nodepool we should only be able to upgrade it to the current HC version.

I agree, the PR is already validating against the HC https://github.com/openshift/hypershift/pull/1709/files#diff-c666a2a9dc48b0d3de33cc8fa3a054f853671f0428f9d56b263750dfc6d26e00R1360-R1365

**Comment by csrwng** [comment]
> I agree, the PR is already validating against the HC as the latest supported version https://github.com/openshift/hypershift/pull/1709/files#diff-c666a2a9dc48b0d3de33cc8fa3a054f853671f0428f9d56b263750dfc6d26e00R1360-R1365

But should we allow a version < HC's (on creation)?

**Comment by enxebre** [comment]
>But should we allow a version < HC's (on creation)?

We can not prevent creation of anything, i.e as soon as the resource is applied it's persisted, then in the backend we do the validation and short circuit reconciliation. In the reconciliation loop there's no means to differentiate between create/update (or may be we could you .generation?). The backend validating against hc.release as latest allowed and letting webhook/cli validate/default to hc.version for creation makes sense to me.

>But should we allow a version < HC's (on creation)?

Did you have something different in mind for this?

**Comment by csrwng** [comment]
As discussed earlier today, it's fine to proceed with this validation and separately enable the webhook to do a more fine grained validation.

**Pull request merged**
