### PR TITLE
CNV-36056:Expose NodeSelector for KubeVirt VMs in NodePool

### PR DESCRIPTION
**Pull request by orenc1**
**What this PR does / why we need it**:
Adding a new NodePool field, `.spec.platform.kubevirt.nodeSelector`, that will influence the placement of the VirtualMachines (virt-launcher pods) on the infra cluster.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # https://issues.redhat.com/browse/CNV-36056

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by bryan-cox** [comment]
/retitle CNV-36056:Expose NodeSelector for KubeVirt VMs in NodePool

**Comment by orenc1** [comment]
/hold
there's an issue with the newly added e2e test

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Pull request merged**
