### PR TITLE
Remove .status from serialized configuration on HCP

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
In the typed configuration we store, we only use the spec struct of each
configuration resource. However, when we serialize it, we include the
entire resource. The stauts resource is not needed and is causing
incompatibility with older OCP versions.

Going forward, the incompatibility should be fixed by #1616. However,
this change is needed to ensure we don't immediately break things while
CPOs in production are upgraded.

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] This change includes unit tests.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by relyt0925** [comment]
major props to the kube wizardry done here :)

**Comment by relyt0925** [comment]
see change: https://github.com/openshift/api/pull/1235 that sparked this change for more details

**Pull request merged**
