### PR TITLE
NO-JIRA: Added markdown for storage table support

### PR DESCRIPTION
**Pull request by reivaj84**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by bryan-cox** [comment]
This looks better than before, but still doesn't look like it should 🤔 - https://deploy-preview-4213--hypershift-docs.netlify.app/how-to/kubevirt/configuring-storage/

**Comment by bryan-cox** [comment]
/retitle NO-JIRA: Added markdown for storage table support

**Comment by reivaj84** [comment]
@bryan-cox would you please share a reference link I can look at to make it better ?

**Comment by jparrill** [comment]
Hey @reivaj84 here it's the documentation around tables: https://squidfunk.github.io/mkdocs-material/reference/data-tables/#usage. Hope this helps.

/approve

**Comment by reivaj84** [comment]
Thanks @jparrill I think the latest commit would be the right format. I Hope :smile:

**Comment by bryan-cox** [comment]
Looks good to me!

**Pull request merged**
