### PR TITLE
e2e: increase budget to only catch extreme situations

### PR DESCRIPTION
**Pull request by sjenning**
**What this PR does / why we need it**:

This increase the budgets to 3x the max we see in CI right now.

Get the periodic passing

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by csrwng** [comment]
```
        --- FAIL: TestUpgradeControlPlane/EnsureAPIBudget/hypershift-operator_no_404_deletes
```

**Comment by csrwng** [comment]
^^ should that one be relaxed as well?

**Comment by sjenning** [comment]
Didn't adjust the small budget watermark.  Updated the budget for CPO deletes as well.

**Comment by sjenning** [comment]
```
=== CONT  TestUpgradeControlPlane/PreTeardownClusterDump
373
    fixture.go:116: Failed to dump cluster: failed to dump hosted cluster: found WARNING: Object got updated more than one time without a no-op update
```

```
{"level":"info","ts":"2022-05-25T02:07:04Z","msg":"WARNING: Object got updated more than one time without a no-op update, this indicates hypershift incorrectly reverting defaulted values","type":"*v1.Deployment","name":"e2e-clusters-2k7vs-example-hdvlm/openshift-apiserver","diff":"  &v1.Deployment{\n  \tTypeMeta:   {Kind: \"Deployment\", APIVersion: \"apps/v1\"},\n  \tObjectMeta: {Name: \"openshift-apiserver\", Namespace: \"e2e-clusters-2k7vs-example-hdvlm\", UID: \"1e1ba38b-c452-49f1-b353-acdb7bb3e28d\", ResourceVersion: \"43356\", ...},\n  \tSpec: v1.DeploymentSpec{\n  \t\tReplicas: &3,\n  \t\tSelector: &{MatchLabels: {\"app\": \"openshift-apiserver\", \"hypershift.openshift.io/control-plane-component\": \"openshift-apiserver\"}},\n  \t\tTemplate: v1.PodTemplateSpec{\n  \t\t\tObjectMeta: v1.ObjectMeta{\n  \t\t\t\t... // 9 identical fields\n  \t\t\t\tDeletionGracePeriodSeconds: nil,\n  \t\t\t\tLabels:                     {\"app\": \"openshift-apiserver\", \"hypershift.openshift.io/control-plane-component\": \"openshift-apiserver\", \"hypershift.openshift.io/hosted-control-plane\": \"e2e-clusters-2k7vs-example-hdvlm\"},\n  \t\t\t\tAnnotations: map[string]string{\n- \t\t\t\t\t\"ca-checksum\":                                             \"74ce6750200a26c45dd3b892ebb60348\",\n  \t\t\t\t\t\"hypershift.openshift.io/release-image\":                   \"registry.build02.ci.openshift.org/ci-op-qhmtk5kh/release@sha256:\"...,\n  \t\t\t\t\t\"openshift-apiserver.hypershift.openshift.io/config-hash\": \"a7593a750506105abd2e497b16496a2b\",\n  \t\t\t\t},\n  \t\t\t\tOwnerReferences: nil,\n  \t\t\t\tFinalizers:      nil,\n  \t\t\t\t... // 2 identical fields\n  \t\t\t},\n  \t\t\tSpec: {Volumes: {{Name: \"work-logs\", VolumeSource: {EmptyDir: &{}}}, {Name: \"config\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"openshift-apiserver\"}, DefaultMode: &420}}}, {Name: \"audit-config\", VolumeSource: {ConfigMap: &{LocalObjectReference: {Name: \"openshift-apiserver-audit\"}, DefaultMode: &420}}}, {Name: \"aggregator-client-ca\", VolumeSource: {Secret: &{SecretName: \"root-ca\", DefaultMode: &420}}}, ...}, InitContainers: {{Name: \"availability-prober\", Image: \"registry.build02.ci.openshift.org/ci-op-qhmtk5kh/stable@sha256:6\"..., Command: {\"/usr/bin/control-plane-operator\", \"availability-prober\", \"--target\", \"https://kube-apiserver:6443/readyz\"}, TerminationMessagePath: \"/dev/termination-log\", ...}, {Name: \"oas-trust-anchor-generator\", Image: \"registry.build02.ci.openshift.org/ci-op-qhmtk5kh/stable@sha256:6\"..., Command: {\"/bin/bash\", \"-c\", \"cp -f /etc/pki/ca-trust/extracted/pem/* /run/ca-trust-generated/\"...}, VolumeMounts: {{Name: \"kube-controller-manager\", MountPath: \"/run/service-ca-signer\"}, {Name: \"oas-trust-anchor\", MountPath: \"/run/ca-trust-generated\"}}, ...}}, Containers: {{Name: \"openshift-apiserver\", Image: \"registry.build02.ci.openshift.org/ci-op-qhmtk5kh/stable@sha256:6\"..., Args: {\"start\", \"--config=/etc/kubernetes/config/config.yaml\", \"--authorization-kubeconfig=/etc/kubernetes/secrets/svc-kubeconfi\"..., \"--authentication-kubeconfig=/etc/kubernetes/secrets/svc-kubeconf\"..., ...}, WorkingDir: \"/var/log/openshift-apiserver\", ...}, {Name: \"socks5-proxy\", Image: \"registry.build02.ci.openshift.org/ci-op-qhmtk5kh/stable@sha256:6\"..., Command: {\"/usr/bin/control-plane-operator\", \"konnectivity-socks5-proxy\"}, Args: {\"run\"}, ...}}, RestartPolicy: \"Always\", ...},\n  \t\t},\n  \t\tStrategy:        {Type: \"RollingUpdate\", RollingUpdate: &{MaxUnavailable: &{IntVal: 1}, MaxSurge: &{IntVal: 3}}},\n  \t\tMinReadySeconds: 0,\n  \t\t... // 3 identical fields\n  \t},\n  \tStatus: {ObservedGeneration: 5, Replicas: 3, UpdatedReplicas: 3, ReadyReplicas: 3, ...},\n  }\n","semanticDeepEqual":false,"updateCount":2}
```

**Pull request merged**
