### PR TITLE
HOSTEDCP-1300: Bump k8s.io/client-go to v0.28.3

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes [HOSTEDCP-1300](https://issues.redhat.com/browse/HOSTEDCP-1300)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by bryan-cox** [comment]
#3196

**Comment by enxebre** [comment]
cc @davidvossel

**Pull request merged**
