### PR TITLE
HOSTEDCP-1773: Featuregate autoprovision

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:

- This PR introduces support for Feature gates using Autoprovisioning as the driving use case.
- Featuregates are enabled via "k8s.io/component-base/featuregate" and using Cluster API featuregates implementation as the main example.
- Autoprovisioning is implemented via karpenter aws native provider. When Autoprovisioning feature gate is enabled:
  - We create a shim NodePool to generate the userdata.
  - We deploy Karpenter aws provider management side watching the guest cluster.
  - We install the Karpenter CRDs in the guest cluster.
  - We automatically approve all CSRs.
  - We watch Karpeneter ec2Classes and inject the right userdata and ami.

In future the implementation and consumer facing APIs of Autoprovision might / might not differ completely. We might /might not choose to integrate karpenter with Cluster API or even use different.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
/hold
to add unit tests

**Comment by JoelSpeed** [comment]
/hold

After some discussion today, we would like to discuss the impact of this change and the long term plan here before we merge. We have some concerns about introducing provider specific implementations, how this will be supported and the implications of having a feature-gated feature where we know the future implementation likely won't behave in the same manor.

Would like to have a conversation with @enxebre @elmiko @sub-mod @newtonheath @celebdor

**Comment by enxebre** [comment]
Feature gates were added via https://github.com/openshift/hypershift/pull/4918.
/close

**Pull request closed without merging**
