### PR TITLE
HOSTEDCP-1683: Use go workspaces

### PR DESCRIPTION
**Pull request by muraee**
**What this PR does / why we need it**:
This solves 2 problems which were introduced when we moved our API to a separate sub module:
1. Duplicate API files: currently all our API is vendored in the main module.
2. API imports in our code are using the vendored version which led to poor UX because local changes to the API are not being reflected immediately in the code until the vendor dir is updated. Also using the IDE "go to" feature will send you to the vendor folder where you can't do any updates/changes.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:

changes(improvements :slightly_smiling_face:) to your dev env:
1. the Hypershift APIs imports now use local code instead of the vendored version, so any changes you do in the API can be used directly, no need to vendor first.
1. I updated the Makefile, so generally you just need to run `make update` to generate all the stuff and update the vendor dir.
1. if you want to vendor manually, you need to use `go work vendor` 
    - `go mod vendor`  will through an error anyway.
1. dependences versions are synced automatically between the main module and api module with `make sync` which is part of `make update`  so most of the times you don't have to update `api/go.mod` file manually.

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by muraee** [comment]
/hold
requires golang-1.22 base image which is not yet available

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
