### PR TITLE
NO-JIRA: cmd/cluster/kubevirt: add a test from dvossel

### PR DESCRIPTION
**Pull request by stevekuznetsov**
cmd/cluster/kubevirt: add a test from dvossel

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

/assign @davidvossel 

Based on #4219

### CODE REVIEW

**Comment by sjenning** [comment]
```
--- FAIL: TestCreateCluster (0.03s)
    --- FAIL: TestCreateCluster/test_from_dvossel (0.01s)
        create_test.go:176: got diff between expected and actual result:
            file: /go/src/github.com/openshift/hypershift/cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_test_from_dvossel.yaml
            diff:
              (
              	"""
              	... // 128 identical lines
              	        cores: 4
              	        memory: 12Gi
            + 	      networkInterfaceMultiqueue: Enable
              	      nodeSelector:
              	        key: val
              	... // 15 identical lines
              	"""
              )
            
            
            If this is expected, re-run the test with `UPDATE=true go test ./...` to update the fixtures.
```

**Comment by stevekuznetsov** [comment]
@sjenning updated

**Comment by stevekuznetsov** [comment]
`8ae2bb428762ba07e22879b1cc79c9102f00ff61` went in without someone asking for a test ...

**Comment by sjenning** [comment]
/override "Red Hat Konflux / hypershift-operator-main-on-pull-request"

**Pull request merged**
