### PR TITLE
NO-JIRA: docs: fixing wrong key name

### PR DESCRIPTION
**Pull request by Tal-or**
**What this PR does / why we need it**:
The key name in the ConfigMap is `tuning` and not `tuned`.
https://github.com/openshift/hypershift/blob/main/hypershift-operator/controllers/nodepool/nodepool_controller.go#L101 

**Which issue(s) this PR fixes** 
Fixes #
N/A

### CODE REVIEW

**Comment by sjenning** [comment]
please run `make make` and commit the changes to generated files

**Comment by Tal-or** [comment]
> please run `make update` and commit the changes to generated files

Sorry I was not aware of this make target. Done

**Pull request merged**
