### PR TITLE
NO-JIRA: Fix issue with release note tool

### PR DESCRIPTION
**Pull request by imain**
Add a more clear error message and return on error in release note tool.  Also add support for an authorization token so we can avoid 403 errors.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by imain** [comment]
> The title seems misleading to me unless I'm missing something. This doesn't fix the issue; it just adds additional context on the error message, right?

Correct! FIxed now :)

**Review by bryan-cox — APPROVED** [review]
/approve

**Comment by bryan-cox** [comment]
/retitle NO-JIRA: Fix issue with release note tool

**Comment by bryan-cox** [comment]
/lgtm cancel
someone else should lgtm

**Comment by bryan-cox** [comment]
/hold cancel
Removing hold that was from tests failing

**Pull request merged**
