### PR TITLE
OCPBUGS-17171: Update OLM catalog image tags

### PR DESCRIPTION
**Pull request by csrwng**
**What this PR does / why we need it**:
OLM catalog images should reference images that correspond to the release

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #OCPBUGS-17171

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by sjenning** [comment]
/override "Pipelines as Code CI / hypershift-operator-main-on-pull-request"

**Comment by csrwng** [comment]
kubevirt error looks like a CI registry flake:
```
error: failed to push image registry.build05.ci.openshift.org/ci-op-tlncpj0d/release:latest: unable to convert the image to a compatible schema version: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by bryan-cox** [comment]
It looks like prow timed out trying to delete HCs issue again. 
```
{"component":"entrypoint","error":"process timed out","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2023-08-04T08:23:37Z"}
```

/test e2e-aws

**Pull request merged**
