### PR TITLE
reduce frequency of leader election for components in the management cluster

### PR DESCRIPTION
**Pull request by relyt0925**
This reduces the leader election frequencies of components that leader elect in the management cluster to the centralized API Server of that cluster. At scale: all these components end up aggregating requests to the API Server and if not reduced appropriately it can cause substantial load on both the etcd database and apiserver memory/cpu usage. The default values previously triggered election updates every 2 seconds. This pr moves those to be 15 seconds which should provide significant alleviation of the pressure the apiserver is experiencing at max scale (440 clusters in a management cluster).

LeaderElectionReleaseOnCancel supporting details:
ClusterAutoscaler does specify it: https://github.com/openshift/kubernetes-autoscaler/blob/release-4.10/cluster-autoscaler/main.go#L453

No possible exposure of the parameter yet for cluster-api:
https://github.com/openshift/cluster-api/blob/release-1.0/main.go#L198

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by sjenning** [comment]
Yeah, bummer there is no flag for releasing the lease :(
https://github.com/kubernetes-sigs/cluster-api/blob/73ff976dbb64c666ea05721120975cb136556811/main.go#L119-L129

@enxebre you ok with waiting for 60s for the lease to timeout? Or do we want to add the flag upstream before we do this?

**Comment by relyt0925** [comment]
Opened this issue for cluster-api:
https://github.com/openshift/cluster-api/issues/157

**Review by alvaroaleman — APPROVED** [review]
thanks!

**Pull request merged**
