### PR TITLE
HOSTEDCP-1032: e2e: ensure default PSA policy is not privileged

### PR DESCRIPTION
**Pull request by sjenning**
https://issues.redhat.com/browse/HOSTEDCP-1032

### CODE REVIEW

**Comment by enxebre** [comment]
nice! beyond this in/out guest cluster admin behaviour, is there anything we could be checking for regressions in the service side that is usually managed by operators but that we "hand craft" via the CPO, e.g.  https://github.com/openshift/hypershift/blob/55a2549d0320c33a9e824a605e8799a1a91a01be/control-plane-operator/controllers/hostedcontrolplane/kas/config.go#L92-L99
And
https://github.com/openshift/hypershift/blob/55a2549d0320c33a9e824a605e8799a1a91a01be/control-plane-operator/hostedclusterconfigoperator/controllers/resources/namespaces/reconcile.go#L8-L16

**Comment by sjenning** [comment]
The `kas/config.go` is what we are testing here.  We could try to admit a privileged pod into `openshift-infra` and make sure it works.

**Comment by sjenning** [comment]
/override "Red Hat Trusted App Pipeline / hypershift-operator-main-on-pull-request"

**Pull request merged**
