### PR TITLE
[release-4.11] Forward from main

### PR DESCRIPTION
**Pull request by alvaroaleman**
Supersedes https://github.com/openshift/hypershift/pull/1644

/cc @enxebre @csrwng 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by hasueki** [comment]
@alvaroaleman @csrwng Any chance we can hold off on backporting https://github.com/openshift/hypershift/pull/1643#issuecomment-1206030641, so can evaluate the impact on the `cluster-image-registry-operator` move on our side of things?

**Comment by relyt0925** [comment]
We shouldn't move the image-registry-operator: that commit should stay only in 4.12 (potentially just a revert)

**Comment by alvaroaleman** [comment]
Leaving that out makes sense, I've updated the PR to not include that change, ptal

**Comment by hasueki** [comment]
Awesome thanks @alvaroaleman

/unhold

**Pull request merged**
