### PR TITLE
HOSTEDCP-710: Make ImageContentSource immutable

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it**:
Makes ImageContentSource immutable

**Which issue(s) this PR fixes**:
Fixes [HOSTEDCP-710](https://issues.redhat.com/browse/HOSTEDCP-710)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

### CODE REVIEW

**Comment by imain** [comment]
Yeah looks good to me.

/lgtm

**Comment by bryan-cox** [comment]
`{  failed to create secret: secrets "e2e-aws" already exists}`

/test e2e-aws

**Comment by relyt0925** [comment]
IBM needs this for when folks move from public endpoint clusters (public registires) to private only endpoint clusters (private registries)

**Pull request merged**
