### PR TITLE
STOR-2136: Give delete permissions to snapshot-operator role

### PR DESCRIPTION
**Pull request by gnufied**
for removing webhook deployment

To be used with https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/219, but this PR can be merged first, so as not to break CI and stuff.

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
from storage POV

**Comment by jsafrane** [comment]
/test hypershift-operator-main-on-pull-request
s390 build failed, I don't have access to logs

**Comment by bryan-cox** [comment]
> /test hypershift-operator-main-on-pull-request s390 build failed, I don't have access to logs

@jsafrane - Yeah there is some konflux issue regarding that. More info here - https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1734036570038589

**Pull request merged**
