### PR TITLE
Cleanup etcd rule manifest in CVO

### PR DESCRIPTION
**Pull request by alvaroaleman**
It seems the CVO has issues applying this (complains that it failed
    because it doesn't exist). We don't care about this, as there is no etcd
    inside the hostedclsuter, so just omit it.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
>Currently, the CVO tries to apply this and the HCCO does the same,
resulting in races.

I don't think this is accurate since the HCCO does not does this. Let's update the desc before merging so people getting here is not confused.

**Comment by alvaroaleman** [comment]
@enxebre updated, ptal

**Comment by alvaroaleman** [comment]
/hold
There seems to be an issue with e2e tests since they got bumped to 4.12

**Comment by alvaroaleman** [comment]
/override ci/prow/e2e-aws-nested

The bug that is being fixed prevents the upgrade test from succeeding when it tries to rollout the previous version

**Pull request merged**
