### PR TITLE
Getting install more resilient against timeouts when defining resources

### PR DESCRIPTION
**Pull request by Nikokolas3270**
**What this PR does / why we need it**:

In this PR we try to define resources using `create` instead of `patch` whenever possible for the `install` command.
Indeed `patch` is taking much more time than `create` (at least on Mac laptops) and may timeout.

In fact **`patch` will only be used in case the resource already exist**... and to be even more resilient, a resource will be deleted and created again if it fail to be patched.

**Which issue(s) this PR fixes**

No ticket for this PR, but we can create one if needed.

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by Nikokolas3270** [comment]
Without this change, the install is failing as follows on my Mac:

```
export AWS_PROFILE=default                                                 
/usr/local/bin/hypershift install \
  --oidc-storage-provider-s3-bucket-name $OIDC_BUCKET_NAME \
  --oidc-storage-provider-s3-credentials $CLUSTER_AWS_CREDS_FILE \
  --oidc-storage-provider-s3-region $REGION
already exists: PriorityClass /hypershift-control-plane
already exists: PriorityClass /hypershift-etcd
already exists: PriorityClass /hypershift-api-critical
already exists: PriorityClass /hypershift-operator
applied Namespace /hypershift
applied ServiceAccount hypershift/operator
applied ClusterRole /hypershift-operator
applied ClusterRoleBinding /hypershift-operator
applied Role hypershift/hypershift-operator
applied RoleBinding hypershift/hypershift-operator
applied Secret hypershift/hypershift-operator-oidc-provider-s3-credentials
applied Deployment hypershift/operator
applied Service hypershift/operator
applied Role hypershift/prometheus
applied RoleBinding hypershift/prometheus
applied ServiceMonitor hypershift/operator
applied PrometheusRule hypershift/metrics
applied CustomResourceDefinition /clusterresourcesetbindings.addons.cluster.x-k8s.io
applied CustomResourceDefinition /clusterresourcesets.addons.cluster.x-k8s.io
applied CustomResourceDefinition /clusterclasses.cluster.x-k8s.io
applied CustomResourceDefinition /clusters.cluster.x-k8s.io
applied CustomResourceDefinition /machinedeployments.cluster.x-k8s.io
<omit>
applied CustomResourceDefinition /ibmvpcmachinetemplates.infrastructure.cluster.x-k8s.io
applied CustomResourceDefinition /kubevirtclusters.infrastructure.cluster.x-k8s.io
Error: Timeout: request did not complete within requested timeout - context deadline exceeded
Timeout: request did not complete within requested timeout - context deadline exceeded
```

Trying to upgrade the dependencies did not help.

**Comment by Nikokolas3270** [comment]
> @Nikokolas3270 against what version of OCP?

Good question indeed. This is an OSD cluster started by one of my colleague yesterday:
```
oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.10.25   True        False         25h     Cluster version is 4.10.25
```

**Comment by enxebre** [comment]
Are you still seeing this? Might it be because your kas/network is throttled?

**Comment by enxebre** [comment]
Closing due to age, feel free to reopen. Thanks!!
/close

**Pull request closed without merging**
