### PR TITLE
avoid no-op status updates to AWSEndpointServices

### PR DESCRIPTION
**Pull request by sjenning**
**What this PR does / why we need it**:

For a normal `AWSEndpointService` resource, we expect to see ~8 updates to the resource

CPO creates
CPO adds finalizer
HO adds finalizer
HO adds subnetIDs to spec
HO updates status EndpointService is not available (waiting on LB)
HO updates status EndpointService is available
CPO updates status Endpoint not yet available (delay and ES being available)
CPO updates status Endpoint is available

On delete, we expect to see 4 updates

HO subnetID removal as a results of `cluster` deletion
HO deletes
CPO finalizer removal
HO finalizer removal

There will be some 409 conflicts sometimes as controllers race but that should be minimal.

Thus in a periodic job with 9 HCs and 2 `AWSEndpointServices` per HC, we expect to see about 12 x 2 x 9 = 216 mutating calls on `AWSEndpointServices`.

Avoiding these no-op status updates should reduce our mutating calls on `AWSEndpointServices` from ~550 to ~225.

~~Did the same thing to HC status update in case the same thing is happening there.~~

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by sjenning** [comment]
something is wrong here
/hold

**Comment by sjenning** [comment]
`TestCreateCluster` is passing consistently but `TestUpgradeControlPlane` is failing to rollout

**Comment by sjenning** [comment]
Dropped the change to the HostedCluster controller
/hold cancel

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
