### PR TITLE
Revert "Revert "HOSTEDCP-1465: Create HCPs with externalDNS on AKS Clusters""

### PR DESCRIPTION
**Pull request by bryan-cox**
Reverts openshift/hypershift#3890

### CODE REVIEW

**Comment by bryan-cox** [comment]
/override "Red Hat Konflux / hypershift-operator-main-on-pull-request"

Konflux is broke atm.

**Comment by csrwng** [comment]
/override "Red Hat Konflux / hypershift-operator-main-on-pull-request"

**Pull request merged**
