### PR TITLE
OCPBUGS-25342: Add extra resources to be encrypted.

### PR DESCRIPTION
**Pull request by imain**
Standalone OCP encrypts various resources at rest in etcd including routes, oauth access tokens etc.  This change makes HCP also encrypt those objects.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by imain** [comment]
Verified it's working!

bash-5.1$ etcdctl get "/kubernetes.io/configmaps/default/kube-root-ca.crt"
/kubernetes.io/configmaps/default/kube-root-ca.crt
00m0hnc:`He.01:awskmskey-303096005:1xK1b <snip gibberish>

**Review by bryan-cox — APPROVED** [review]
/lgtm

**Pull request merged**
