### PR TITLE
Bump k8s.io go pkgs to v0.26.1 and bump other major pkgs

### PR DESCRIPTION
**Pull request by dharaneeshvrd**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
@dharaneeshvrd do we still need this or can we close it?

**Comment by dharaneeshvrd** [comment]
PR is not required now, will close it.

**Pull request closed without merging**
