### PR TITLE
add KAS egress network policy

### PR DESCRIPTION
**Pull request by sjenning**
https://issues.redhat.com/browse/HOSTEDCP-645

### CODE REVIEW

**Comment by csrwng** [comment]
@hasueki @relyt0925 ptal
lgtm

**Comment by sjenning** [comment]
/hold
All tests failed unable to connect to the guest KAS.  Not sure if this works as OSD claimed.

**Comment by enxebre** [comment]
/hold
to make sure it doesn't trigger CI before https://github.com/openshift/hypershift/pull/1970 gets merged

**Comment by hasueki** [comment]
This egress policy was blocking DNS traffic when installed on vanilla kube mgmt clusters.
```
E0105 18:18:14.955429       1 run.go:74] "command failed" err="context deadline exceeded"
W0105 18:18:14.955429       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "etcd-prtesting412-82267746-client:2379",
  "ServerName": "etcd-prtesting412-82267746-client",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup etcd-prtesting412-82267746-client: i/o timeout"
```
Altering it to..
```
MatchLabels: map[string]string{
    "kubernetes.io/metadata.name": "kube-system",
},
```
.. seems to work for vanilla kube.

**Pull request merged**
