### PR TITLE
OCPBUGS-15168: fix(oauth): Do not proxy IBM Cloud IAM endpoints

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by relyt0925** [comment]
Details in this issue:
https://issues.redhat.com/browse/OCPBUGS-15168

**Comment by bryan-cox** [comment]
> I think @bryan-cox change drop the explicit injection of the no proxy url here [5f408d3](https://github.com/openshift/hypershift/commit/5f408d33558b9850ed619ded7bf05929bea5e161)
> 
> because the exception would be made by the socks5 resolver via `isCloudAPI`
> 
> @bryan-cox Is there a bug in that code 2366 so we'd need to consolidate it with this change?

I think there may be a bug, but it was introduced in #2261

**Comment by relyt0925** [comment]
Specifically:
the bug here at least in this regard is there is since connect-directly-to-cloud-endpoints by default is set to false: that change introduced a behavior change that now led to proxying of iam traffic in the oauth server

I believe in future releases this should by default be true:
https://github.com/openshift/hypershift/blob/main/konnectivity-socks5-proxy/main.go#L61

**Pull request merged**
