### PR TITLE
Add Kubevirt platform quick start docs

### LINKED ISSUE #961: Create Kubevirt Platform quick start docs
As part of adding new Kubevirt Platform to the Hypershift project, need also to add quick start docs
This is needed in order to gain platform stability and to have the option to try and test it by external users

### PR DESCRIPTION
**Pull request by nirarg**
**What this PR does / why we need it**:

In order to have more platform stability and test ability, add this quick
start guide to allow external users to use it
This is added as a second platform after AWS platform quick start guide

**Which issue(s) this PR fixes**:
Fixes #961 

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [x] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
awesome, thanks! let's way to close this discussion before moving forward https://github.com/openshift/hypershift/pull/979#issuecomment-1032395947

**Comment by enxebre** [comment]
can you move to how-to/ for consistency with https://github.com/openshift/hypershift/pull/979?

**Comment by nirarg** [comment]
> can you move to how-to/ for consistency with #979?

@enxebre done, please review

**Comment by enxebre** [comment]
thanks @nirarg, I want ahead and rebased your branch to resolve the conflict.
/approve
/lgtm

**Comment by nirarg** [comment]
Thanks @enxebre

**Pull request merged**
