### PR TITLE
Revert "Merge pull request #2596 from muraee/disable-valpha1"

### PR DESCRIPTION
**Pull request by sjenning**
This reverts commit 74c336e5e5e9bf65cebb4101d591c492a07ccf62, reversing changes made to d5a31a74718dea331658a15f54c83cda71e3c98d.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
@sjenning is the commit in the PR desc https://github.com/openshift/hypershift/commit/d5a31a74718dea331658a15f54c83cda71e3c98d the wrong one?

https://github.com/openshift/hypershift/pull/2596#issuecomment-1570346791

Is this CNO still applying v1alpha1 resource? Is conversion still enabled in the CRD definition there? cc @muraee

**Comment by stbenjam** [comment]
> @sjenning is the commit in the PR desc https://github.com/openshift/hypershift/commit/d5a31a74718dea331658a15f54c83cda71e3c98d the wrong one?

No, 74c336e is what's being reverted. d5a31a7 is mentioned because it's the prior commit that this was merged with, it's boilerplate text generated by git when you revert.

**Comment by muraee** [comment]
@enxebre an old 4.13 release version `4.13.0-0.nightly-2023-01-17-084735` is used in our CI for some reason which doesn't include the CNO PR https://github.com/openshift/cluster-network-operator/pull/1802 to switch to `v1beta1`

**Pull request merged**
