### PR TITLE
[Kubevirt] Remove EgressFirewall Creation in HCP namespace

### PR DESCRIPTION
**Pull request by orenc1**
Starting from 4.14, the EgressFirewall is not needed any longer, since kubevirt platform consumes the kubevirt provider in RHCOS, thus an attempt to access the metadata server is not being initiated, as opposed to the legacy OpenStack RHCOS provider.
Therefore, EgressFirewall is not needed to be deployed on the mgmt/infra cluster for guests >= v4.14.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by qinqon** [comment]
I think we can remove the egressfirewall thing altogether from hypershift >= 4.14. What do you think @davidvossel ?

**Comment by orenc1** [comment]
> I think we can remove the egressfirewall thing altogether from hypershift >= 4.14. What do you think @davidvossel ?

but we have an annotation of `hypershift.openshift.io/allow-unsupported-kubevirt-rhcos-variants` that can potentially allow creation of guest clusters of <= 4.13.
if we'll remove it from main/4.14, users won't be able to create guest clusters of lower minor versions.

do we want to remove that escape hatch?

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
