### PR TITLE
[release-4.11] Fix nil pointer dereference for hostedControlPlane.Spec.Etcd.Managed

### PR DESCRIPTION
**Pull request by enxebre**
This prevents the backend from panicking and move defaulting into the API to avoid self hcp updating spec and skew from HC

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
OCP 4.11 GA in plan imminently. Let's merge this + anything else in a z stream so MCE can consume it from there unless there's any objection.

**Comment by alvaroaleman** [comment]
> OCP 4.11 GA is imminent. Let's merge this + anything else in a z stream so MCE can consume it from there unless there's any objection.

Right, so just fast-forward the branch so we get everything? We are currently unable to run conformance tests with 4.12 so it would be good to have an up-to-date branch where we can.

**Comment by alvaroaleman** [comment]
Merging a single backport like this breaks the ability to fast-forward I think

**Comment by sjenning** [comment]
#1655 included this

**Pull request closed without merging**
