### PR TITLE
OCPBUGS-33713: Reconcile over ICSP/IDMS

### PR DESCRIPTION
**Pull request by jparrill**
This is a manual backport of https://github.com/openshift/hypershift/pull/3860

Now the hypershift operator does not ignore RegistryOverrides and the metadata inspection works as expected

Which issue(s) this PR fixes :
Fixes #[OCPBUGS-29494](https://issues.redhat.com/browse/OCPBUGS-29494)

**Important NOTE:** *This PR has been adapted because the manual cherry pick needed things that they are not present in the 4.14 release*

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 --- FAIL: TestHostedClusterWatchesEverythingItCreates (0.24s)
    --- FAIL: TestHostedClusterWatchesEverythingItCreates/agent (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x29fc5c4]
goroutine 138 [running]:
testing.tRunner.func1.2({0x2cba6e0, 0x553f190})
	/usr/lib/golang/src/testing/testing.go:1526 +0x372
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1529 +0x650
panic({0x2cba6e0, 0x553f190})
	/usr/lib/golang/src/runtime/panic.go:890 +0x263
github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster.(*HostedClusterReconciler).reconcile(0xc000bfe240, {0x42c43b8, 0xc000232008}, {{{0x0, 0x0}, {0x2f9bcc1, 0x5}}}, {{0x42c70f8, 0xc000ba7830}, 0x0}, ...)
	/go/src/github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:1080 +0xb504
github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster.(*HostedClusterReconciler).Reconcile(0xc000bfe240, {0x42c43b8, 0xc000232008}, {{{0x0, 0x0}, {0x2f9bcc1, 0x5}}})
	/go/src/github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:304 +0x645
github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster.TestHostedClusterWatchesEverythingItCreates.func4(0xc00081f040)
	/go/src/github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go:992 +0xf3
testing.tRunner(0xc00081f040, 0xc00058ca98)
	/usr/lib/golang/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1629 +0x806 
```

**Comment by jparrill** [comment]
> ```
>  --- FAIL: TestHostedClusterWatchesEverythingItCreates (0.24s)
>     --- FAIL: TestHostedClusterWatchesEverythingItCreates/agent (0.00s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x29fc5c4]
> goroutine 138 [running]:
> testing.tRunner.func1.2({0x2cba6e0, 0x553f190})
> 	/usr/lib/golang/src/testing/testing.go:1526 +0x372
> testing.tRunner.func1()
> 	/usr/lib/golang/src/testing/testing.go:1529 +0x650
> panic({0x2cba6e0, 0x553f190})
> 	/usr/lib/golang/src/runtime/panic.go:890 +0x263
> github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster.(*HostedClusterReconciler).reconcile(0xc000bfe240, {0x42c43b8, 0xc000232008}, {{{0x0, 0x0}, {0x2f9bcc1, 0x5}}}, {{0x42c70f8, 0xc000ba7830}, 0x0}, ...)
> 	/go/src/github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:1080 +0xb504
> github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster.(*HostedClusterReconciler).Reconcile(0xc000bfe240, {0x42c43b8, 0xc000232008}, {{{0x0, 0x0}, {0x2f9bcc1, 0x5}}})
> 	/go/src/github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go:304 +0x645
> github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster.TestHostedClusterWatchesEverythingItCreates.func4(0xc00081f040)
> 	/go/src/github.com/openshift/hypershift/hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go:992 +0xf3
> testing.tRunner(0xc00081f040, 0xc00058ca98)
> 	/usr/lib/golang/src/testing/testing.go:1576 +0x217
> created by testing.(*T).Run
> 	/usr/lib/golang/src/testing/testing.go:1629 +0x806 
> ```

Yep, no worries, it was a complicated backport. Now should be ok

**Pull request merged**
