### PR TITLE
[release-4.15] OCPBUGS-30651: Remove EnsurePSANotPrivileged

### PR DESCRIPTION
**Pull request by rtheis**
Full revert of [1] and partial revert of [2].

[1] https://github.com/openshift/hypershift/pull/3107
[2] https://github.com/openshift/hypershift/pull/3137

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # [OCPBUGS-30651](https://issues.redhat.com/browse/OCPBUGS-30651)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [x] This change includes unit tests.

### CODE REVIEW

**Comment by rtheis** [comment]
I don't see how the failure logs have any relation to this PR.

**Comment by rtheis** [comment]
Per https://ibm-argonauts.slack.com/archives/C01C8502FMM/p1710414602696739, the test problem may be resolved.

**Review by hasueki — APPROVED** [review]
/lgtm

**Comment by hasueki** [comment]
/retitle [release-4.15] OCPBUGS-30651: Remove EnsurePSANotPrivileged

**Pull request merged**
