### PR TITLE
HOSTEDCP-1558: use openshift/api instead of thirdparty for machineconfig

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Comment by celebdor** [comment]
/retitle HOSTEDCP-1558: use openshift/api instead of thirdparty for machineconfig

**Comment by stevekuznetsov** [comment]
/retitle HOSTEDCP-1558: use openshift/api instead of thirdparty for machineconfig
/assign @enxebre

**Comment by enxebre** [comment]
Thanks!
/approve
/hold
to wait for 4.17

**Comment by enxebre** [comment]
Thanks!
/lgtm

**Comment by csrwng** [comment]
/override "Red Hat Konflux / hypershift-operator-main-on-pull-request"

**Pull request merged**
