### PR TITLE
OCPBUGS-11738: Delete kubeadmin secret when an idp is defined

### PR DESCRIPTION
**Pull request by muraee**
**What this PR does / why we need it**:
this removes "kube:admin" IdP as an available option when an explicit idp is defined

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #[OCPBUGS-11738](https://issues.redhat.com/browse/OCPBUGS-11738)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
I think we also need to update the logic to reset the `.Status.KubeadminPassword` from both HC and HCP.
Please let's also add an e2e validation that check the above is set/unset consistently  as part of the iDP e2e

**Comment by sjenning** [comment]
/hold
seems to be a legit failure, remove when updated

**Pull request merged**
