### PR TITLE
ensure tokens aren't removed until all references are confirmed to be  removed to prevent unecessary config generation and registry calls

### PR DESCRIPTION
**Pull request by relyt0925**
This solves a race condition where right after a secret is patched on rotation: a reconciliation loop is triggered, the ignition server reads an older value of the secret from it's local cache that contains a reference to the rotated secret, notices that it does not exist locally in the cache, and then proceeds to regenerate the entry resulting in an additional registry call.

Additionally there is a case where when a token that stays around for a period of time after a config update (to process in flight provisions) can get it's tokens removed from the payload store resulting in extra registry calls needing to be made to regenerate that config.

By ensuring there is some overhead time on the cache entry expiry and relying on the background process to clean tokens versus explicitly calling revocation: we can continue to properly utilize the cache client which is important from a load perspective and still get the ultimate desired periodic rotation process.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
>This solves a race condition where right after a secret is patched on rotation: a reconciliation loop is triggered, the ignition server reads an older value of the secret from it's local cache that contains a reference to the rotated secret, notices that it does not exist locally in the cache, and then proceeds to regenerate the entry resulting in an additional registry call.

When this happens the deleted token should have been in the rotated spot for ttl/2 i.e 5.5h, which should have been more than enough for any in flight operation to happen, unless there's a place where we/you are not updating the source request with the token. Do you agree?

**Comment by relyt0925** [comment]
I agree with your statement on “not used in active provisioning requests”. But what I am pointing out in this is that doesn’t matter when it comes to the reconciliation loop and generating the content

The loop is isolated from the provisioning requests. In the loop it is just looking at the existence of secrets and their associated keys

**Comment by enxebre** [comment]
>The loop is isolated from the provisioning requests. In the loop it is just looking at the existence of secrets and their associated keys

ah you're right, I see what you mean. Still a secret from a stale kube client cache should be pointing to the token in the rotated spot which must exist in the payload cache, not to the one rotated out completely that wouldn't exist in the payload cache, right?

/hold
As discussed in slack let me try to get to the bottom of this before proceeding with the PR.

**Comment by relyt0925** [comment]
@enxebre would be interested in your findings when you have them!

**Comment by enxebre** [comment]
superseded by https://github.com/openshift/hypershift/pull/1523

**Pull request closed without merging**
