### PR TITLE
add health probes to ingress operator to ensure it is functioning

### PR DESCRIPTION
**Pull request by relyt0925**
Looking at the ingress operator code:
https://github.com/openshift/cluster-ingress-operator/blob/master/cmd/ingress-operator/start.go#L74

The only possible "web probe" to call is the prometheus endpoint hence why I added this to be the initial probe for readiness and liveliness. In the future if a probe option was exposed to have a health endpoint we could move to using that.

It's critical to have liveness and readiness probes on components in the controlplane to be able to account and monitor for oddities in the programs over time (even if it seems like the program is setup to "never fail").

We should brainstorm if there's some clever way to do this in the token minter as well if that is part of operations

### CODE REVIEW

**Comment by relyt0925** [comment]
also tested in IBMCloud
```
ingress-operator-84bcf7d6cc-74sj8                2/2     Running     0          4m13s   172.30.94.166    10.36.179.178    <none>           <none>
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 172.30.94.166/32
    cni.projectcalico.org/podIPs: 172.30.94.166/32
    kubernetes.io/psp: ibm-privileged-psp
    target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  creationTimestamp: "2022-01-20T04:06:29Z"
  generateName: ingress-operator-84bcf7d6cc-
  labels:
    hypershift.openshift.io/hosted-control-plane: master-prtesting410-62532583
    name: ingress-operator
    pod-template-hash: 84bcf7d6cc
  name: ingress-operator-84bcf7d6cc-74sj8
  namespace: master-prtesting410-62532583
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ingress-operator-84bcf7d6cc
    uid: dd4120b7-b135-478a-baf7-3fff7c5e4650
  resourceVersion: "28481770"
  uid: a6207aaf-eb60-4471-a9b3-d3132d14d8fe
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: hypershift.openshift.io/control-plane
            operator: In
            values:
            - "true"
        weight: 50
      - preference:
          matchExpressions:
          - key: hypershift.openshift.io/cluster
            operator: In
            values:
            - master-prtesting410-62532583
        weight: 100
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              hypershift.openshift.io/hosted-control-plane: master-prtesting410-62532583
          topologyKey: kubernetes.io/hostname
        weight: 100
  automountServiceAccountToken: false
  containers:
  - command:
    - ingress-operator
    - start
    - --namespace
    - openshift-ingress-operator
    - --image
    - $(IMAGE)
    - --canary-image
    - $(CANARY_IMAGE)
    - --release-version
    - $(RELEASE_VERSION)
    - --metrics-listen-addr
    - 0.0.0.0:60000
    env:
    - name: RELEASE_VERSION
      value: 4.9.15
    - name: IMAGE
      value: registry.ng.bluemix.net/armada-master/ocp-release@sha256:038452cc237d09fbbea348a454007760fb2d04e1e2439e931c505665c2c98071
    - name: CANARY_IMAGE
      value: registry.ng.bluemix.net/armada-master/ocp-release@sha256:df22255abc474a2b61b323925f76126fa2f8c99affb1c48c2a0eb16c4b4a1056
    - name: KUBECONFIG
      value: /etc/kubernetes/kubeconfig
    image: registry.ng.bluemix.net/armada-master/ocp-release@sha256:df22255abc474a2b61b323925f76126fa2f8c99affb1c48c2a0eb16c4b4a1056
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /metrics
        port: 60000
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 5
    name: ingress-operator
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: 60000
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 10m
        memory: 56Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: ingress-operator-kubeconfig
    - mountPath: /var/run/secrets/openshift/serviceaccount
      name: serviceaccount-token
  - args:
    - -service-account-namespace=openshift-ingress-operator
    - -service-account-name=ingress-operator
    - -token-file=/var/run/secrets/openshift/serviceaccount/token
    - -kubeconfig=/etc/kubernetes/kubeconfig
    command:
    - /usr/bin/token-minter
    image: registry.ng.bluemix.net/armada-master/armada-hypershift-operator:1799e1c7b2e406827c1c1047ab1cb9855ed90d4b
    imagePullPolicy: IfNotPresent
    name: token-minter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/openshift/serviceaccount
      name: serviceaccount-token
    - mountPath: /etc/kubernetes
      name: admin-kubeconfig
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: pull-secret
  initContainers:
  - command:
    - /usr/bin/availability-prober
    - --target
    - https://kube-apiserver:2040/readyz
    - --kubeconfig=/var/kubeconfig/kubeconfig
    - --required-api=route.openshift.io,v1,Route
    image: registry.ng.bluemix.net/armada-master/armada-hypershift-operator:1799e1c7b2e406827c1c1047ab1cb9855ed90d4b
    imagePullPolicy: Always
    name: availability-prober
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/kubeconfig
      name: ingress-operator-kubeconfig
  nodeName: 10.36.179.178
  preemptionPolicy: PreemptLowerPriority
  priority: 100000000
  priorityClassName: hypershift-control-plane
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: hypershift.openshift.io/control-plane
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: hypershift.openshift.io/cluster
    operator: Equal
    value: master-prtesting410-62532583
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 600
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 600
  volumes:
  - emptyDir: {}
    name: serviceaccount-token
  - name: admin-kubeconfig
    secret:
      defaultMode: 420
      secretName: service-network-admin-kubeconfig
  - name: ingress-operator-kubeconfig
    secret:
      defaultMode: 420
      secretName: ingress-operator-kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-20T04:09:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-20T04:10:00Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-20T04:10:00Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-01-20T04:06:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d3d3b58aa657fa4b8846bed6d4b0c91cca203afa3f2d1ea5ad96b419795a1625
    image: sha256:85eb1eba8745c22b36bd85cf97febb02567f13a5c98e5decc38ed726a6167c87
    imageID: registry.ng.bluemix.net/armada-master/ocp-release@sha256:df22255abc474a2b61b323925f76126fa2f8c99affb1c48c2a0eb16c4b4a1056
    lastState: {}
    name: ingress-operator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-01-20T04:09:37Z"
  - containerID: containerd://7f38377e0676dc2d6014ba8388f41e4bd3ddafb460f5ce78bf26c9810227ae48
    image: registry.ng.bluemix.net/armada-master/armada-hypershift-operator:1799e1c7b2e406827c1c1047ab1cb9855ed90d4b
    imageID: registry.ng.bluemix.net/armada-master/armada-hypershift-operator@sha256:367ad9a06ab3739bb18d1a0a5d39460b48d5894d7c430ed2af4b6292c9b7bead
    lastState: {}
    name: token-minter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-01-20T04:09:41Z"
  hostIP: 10.36.179.178
  initContainerStatuses:
  - containerID: containerd://310883f5c650ca6cf11b8604ff971747076e5b6daa91865402e76b3ad8b94899
    image: registry.ng.bluemix.net/armada-master/armada-hypershift-operator:1799e1c7b2e406827c1c1047ab1cb9855ed90d4b
    imageID: registry.ng.bluemix.net/armada-master/armada-hypershift-operator@sha256:367ad9a06ab3739bb18d1a0a5d39460b48d5894d7c430ed2af4b6292c9b7bead
    lastState: {}
    name: availability-prober
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://310883f5c650ca6cf11b8604ff971747076e5b6daa91865402e76b3ad8b94899
        exitCode: 0
        finishedAt: "2022-01-20T04:09:29Z"
        reason: Completed
        startedAt: "2022-01-20T04:06:34Z"
  phase: Running
  podIP: 172.30.94.166
  podIPs:
  - ip: 172.30.94.166
  qosClass: Burstable
  startTime: "2022-01-20T04:06:29Z"
```

**Comment by enxebre** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
