### PR TITLE
non root daemonset (isn't done by default in the kube-system namespace)

### PR DESCRIPTION
**Pull request by relyt0925**

### CODE REVIEW

**Comment by relyt0925** [comment]
confirmed this is the default pod yaml
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-07-01T22:34:04Z"
  generateName: konnectivity-agent-
  labels:
    app: konnectivity-agent
    controller-revision-hash: 55768778d7
    pod-template-generation: "1"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:controller-revision-hash: {}
          f:pod-template-generation: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4b5b924a-764e-41f1-b46a-6082c06df8f6"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution:
              .: {}
              f:nodeSelectorTerms: {}
        f:containers:
          k:{"name":"konnectivity-agent"}:
            .: {}
            f:args: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/konnectivity/agent"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"agent-certs"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-07-01T22:34:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-scheduler
    operation: Update
    time: "2021-07-01T22:34:04Z"
  name: konnectivity-agent-l7bkz
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: konnectivity-agent
    uid: 4b5b924a-764e-41f1-b46a-6082c06df8f6
  resourceVersion: "123952"
  uid: d2e0abe6-b561-48d8-bb99-063c8e0cebf9
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - tyler-19
  containers:
  - args:
    - --logtostderr=true
    - --ca-cert
    - /etc/konnectivity/agent/ca.crt
    - --agent-cert
    - /etc/konnectivity/agent/tls.crt
    - --agent-key
    - /etc/konnectivity/agent/tls.key
    - --proxy-server-host
    - tyler-hypershift-te-15b0bf3714b2d9d344c3b8647edb7860-0000.us-south.stg.containers.appdomain.cloud
    - --proxy-server-port
    - "31488"
    - --agent-identifiers=default-route=true
    command:
    - /proxy-agent
    image: registry.ng.bluemix.net/armada-master/proxy-agent-amd64:1902237afd2a09241101b512da4feb65276861c8
    imagePullPolicy: Always
    name: konnectivity-agent
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/konnectivity/agent
      name: agent-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-5c2nn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-9t22p
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - name: agent-certs
    secret:
      defaultMode: 420
      secretName: konnectivity-agent
  - name: default-token-5c2nn
    secret:
      defaultMode: 420
      secretName: default-token-5c2nn
```

**Comment by relyt0925** [comment]
looks good after security context
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-07-08T21:09:13Z"
  generateName: konnectivity-agent-
  labels:
    app: konnectivity-agent
    controller-revision-hash: 7b6f7577bb
    pod-template-generation: "2"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:controller-revision-hash: {}
          f:pod-template-generation: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4b5b924a-764e-41f1-b46a-6082c06df8f6"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution:
              .: {}
              f:nodeSelectorTerms: {}
        f:containers:
          k:{"name":"konnectivity-agent"}:
            .: {}
            f:args: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/konnectivity/agent"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:runAsUser: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"agent-certs"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-07-08T21:09:13Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-scheduler
    operation: Update
    time: "2021-07-08T21:09:13Z"
  name: konnectivity-agent-2g89k
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: konnectivity-agent
    uid: 4b5b924a-764e-41f1-b46a-6082c06df8f6
  resourceVersion: "3869186"
  uid: ed6e5e51-ecfb-4ebe-b34e-51f8462fdafa
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - tyler-19
  containers:
  - args:
    - --logtostderr=true
    - --ca-cert
    - /etc/konnectivity/agent/ca.crt
    - --agent-cert
    - /etc/konnectivity/agent/tls.crt
    - --agent-key
    - /etc/konnectivity/agent/tls.key
    - --proxy-server-host
    - tyler-hypershift-te-15b0bf3714b2d9d344c3b8647edb7860-0000.us-south.stg.containers.appdomain.cloud
    - --proxy-server-port
    - "31488"
    - --agent-identifiers=default-route=true
    command:
    - /usr/bin/proxy-agent
    image: registry.ci.openshift.org/hypershift/apiserver-network-proxy:latest
    imagePullPolicy: Always
    name: konnectivity-agent
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/konnectivity/agent
      name: agent-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-5c2nn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-9t22p
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - name: agent-certs
    secret:
      defaultMode: 420
      secretName: konnectivity-agent
  - name: default-token-5c2nn
    secret:
      defaultMode: 420
      secretName: default-token-5c2nn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-08T21:09:13Z"
    message: '0/1 nodes are available: 1 Insufficient cpu.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

**Comment by sjenning** [comment]
/approve
wait for e2e before lgtm

**Pull request merged**
