### PR TITLE
HOSTEDCP-1447: test/e2e: tar.gz hosted cluster content

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Our end-to-end tests take forever to load in Deck directly due to the number of files we have in the artifact directory. Generally, jobs will archive the results to improve this.

/assign @sjenning

### CODE REVIEW

**Comment by sjenning** [comment]
/lgtm
/hold
until we inspect e2e-aws artifacts and verify the hosted cluster artifacts are tar.gz'd as expected

**Comment by stevekuznetsov** [comment]
Well, it works, but loading is still slow ... will have to do more digging into what is eating up so many files in GCS.

**Pull request merged**
