### PR TITLE
[release-4.12] HOSTEDCP-568: Update Konnectiviy socks5 proxy for IBM exception

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it**:
Manual cherry-pick of #2366

### CODE REVIEW

**Comment by enxebre** [comment]
cherry-pick doesn't play well with the branch
```
CGO_ENABLED=0 GO111MODULE=on GOFLAGS=-mod=vendor go build -gcflags=all='-N -l' -o bin/control-plane-operator ./control-plane-operator
# github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go:1783:45: undefined: manifests.ClusterNodeTuningOperatorServingCertSecret
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go:1785:9: undefined: removeServiceCAAnnotationAndSecret
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go:1790:14: undefined: pki.ReconcileNodeTuningOperatorServingCertSecret
```

**Comment by bryan-cox** [comment]
#2293 was merged.
/unhold

**Pull request merged**
