### PR TITLE
Add ownerRef to clusters generated secrets

### LINKED ISSUE #152: Should hypershift destroy remove the clusters/[Name]-pull-secret
If you run the `hypershift destroy cluster ...` command it doesn't clean up the `clusters\example-pull-secret` - which means on a subsequent run to recreate your cluster (maybe there was an issue and want to start over) the same potentially bad pull-secret is in the cluster. 

Should destroy also clean this on each run since we *require* the `--pull-secret` parameter on the `create cluster` command?

### PR DESCRIPTION
**Pull request by screeley44**
Fixes #152 

I was hacking around, not sure if there is a cleaner way to add this, but it does trigger garbage collection and when the HostedCluster is deleted, the secrets are not left around anymore in `clusters/*`

### CODE REVIEW

**Comment by sjenning** [comment]
This topic has come up before.  Do we want the secrets to be owned by a `HostedCluster`?

I could foresee a situation where multiple `HostedClusters` share, say, the same `aws-creds`, creating multiple guest clusters in the same account.

**Comment by sjenning** [comment]
Also, the PR makes changes unrelated to changing the secret owner refs.

**Comment by screeley44** [comment]
@sjenning - yeah, sorry about that, I fixed up the commit

yeah, I'm not sure what conversations you all had about this but from my novice opinion it makes sense that these are owned by the hostedcluster (specifically the `clusters/mycluster-*` secrets - I don't see any benefit of these hanging around after a cluster is destroyed especially since the secrets are sync'd/propagated to the HCP namespace and some in the `openshift-config` directory 

so the ownerRef is only applied to the secrets in the `clusters` NS, there is no ownerRef on the HCP secrets that are sync'd

thoughts?

**Comment by enxebre** [comment]
This secretes are pre-created ahead of time. Also they can technically be shared between HC.
Is there a reason why we'd want to include this ownerRef?

**Comment by screeley44** [comment]
ok, I think that makes sense, you mention they can be shared...is there a param in the `create cluster` that let's me reuse an already existing HC secret or is this something that is coming down the road? 

If they can be shared, I guess you're saying, when we destroy a HC we may not want to remove any of the secrets in `clusters` NS (behavior today). Does that have any security implications? Maybe a flag on the `destroy` command that indicates if we want to clean up these secrets? Or do we not care and let the admins clean up orphaned secrets?
@enxebre @sjenning

**Comment by ironcladlou** [comment]
I have a clear idea of how this could be done and haven't had the time... In [cluster/create.go](https://github.com/openshift/hypershift/blob/main/cmd/cluster/create.go#L220), instead of getting a list of objects to blindly apply, refactor to create object and persist them sequentially like any other reconciliation flow. As you go, establish owner refs between things as necessary. I think that's all there is to it.

I do not think the controllers should know anything about these relationships — after all, at the end of the day the HostedCluster and its secrets that are referenced belong to the end user. It's up to them to establish relationships (if any) to serve their needs.

/hold

**Comment by enxebre** [comment]
>Or do we not care and let the admins clean up orphaned secrets?

I don't see them as orphaned. The hostedCluster does not create them. They are prerequisites that a hostedCluster CR choose to reference.
We just happen to automate the creation and references through a convenient CLI.

**Comment by ironcladlou** [comment]
> > Or do we not care and let the admins clean up orphaned secrets?
> 
> I don't see them as orphaned. The hostedCluster does not create them. They are prerequisites that a hostedCluster CR choose to reference.
> We just happen to automate the creation and references through a convenient CLI.

The CLI is opinionated enough to scope the secret to the specific cluster is created, and the CLI also tears down everything else related to the cluster it created. But not the secrets, which are now named like they're associated with a cluster that no longer exists. If the CLI were ensuring a long-lived shared secret used by all clusters created by the CLI (and the CLI had an option to reference a secret name) that might make some sense to leave them around. Otherwise it just seems to me (and I think to others outside the who have used the CLI?) like confusing and useless leftovers.

Just my subjective opinion.

Of course our end users won't be using any of this CLI stuff at all, so I will go with whatever seems least surprising/most useful to the developers encountering the CLI. Would love additional feedback from others.

**Comment by ironcladlou** [comment]
Talked this over some more with @enxebre and I think we reached the following conclusions:

1. We do want the CLI to clean up after itself, deleting anything it created (e.g. the pull secret)
2. This is purely a client concern (i.e. the logic should be encapsulated entirely within the CLI create/destroy code)
3. We will avoid relying on the k8s GC (i.e. owner refs) to handle the cleanup in this case and would prefer for the CLI to do the tracking and cleanup itself

**Comment by screeley44** [comment]
Closing this for new proposed approach - keeping for reference

**Pull request closed without merging**
