### PR TITLE
Refactor e2e test common cleanup

### PR DESCRIPTION
**Pull request by enxebre**
**What this PR does / why we need it**:
Run the Ensure* validations in the generic create cluster to avoid maintining the list in each individual test.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
cc @sjenning

**Comment by alvaroaleman** [comment]
@enxebre The tests in `t.Cleanup` currently fail because their context is cancelled

**Comment by enxebre** [comment]
>@enxebre The tests in t.Cleanup currently fail because their context is cancelled

updated.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
