### PR TITLE
Add support for specifying Kube API server advertise address/port

### PR DESCRIPTION
**Pull request by csrwng**
Why is this needed? In hypershift clusters, we run an HA proxy server on
each worker. This HA proxy server listens on a local interface and sends
traffic to the external control plane endpoint. To listen on the local
interface, we assign a dummy address to the loopback device and make
that the API server's advertise address. In some cases, it may be
necessary to change what this dummy address is to not interfere with
valid network address ranges in the customer's environment. This change
allows specifying that through the API.

The secure port at which the API server listens is also the same port at
which the HA proxy must listen on worker nodes. In the case of ROKS,
this has historically been different than the default (2040 instead of
6443). It may also be necessary to modify this port to not interfere
with pods listening on ports that are bound to the host network on
worker nodes.

### CODE REVIEW

**Comment by sjenning** [comment]
do we need to change these?

https://github.com/openshift/hypershift/blob/a86c74d2528991839e09725660b56dfa5fddbca3/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go#L68

https://github.com/openshift/hypershift/blob/a86c74d2528991839e09725660b56dfa5fddbca3/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go#L1684

**Comment by relyt0925** [comment]
this prototype pr might help:
https://github.com/relyt0925/hypershift/pull/24

**Comment by csrwng** [comment]
/hold cancel
This is working just as well as the main branch. While testing it, discovered that there's an issue with the communication between the kube apiserver and worker kubelets (`oc get logs` is not working). However, the issue is present in the main branch as well.

**Comment by relyt0925** [comment]
this is a very exciting milestone :) great work all!

**Pull request merged**
