### PR TITLE
OCPBUGS-41935: Sanitize the IgnitionPayload (XSS)

### PR DESCRIPTION
**Pull request by jparrill**
Snyk Duty task

**Which issue(s) this PR fixes** :
Fixes #[OCPBUGS-41935](https://issues.redhat.com/browse/OCPBUGS-41935)

### CODE REVIEW

**Comment by celebdor** [comment]
I can confirm it addresses the snyk static code analysis issue:
`❯ git cherry-pick jparrill/OCPBUGS-41935
[HOSTEDCP-1965 cf8ca6a9b] OCPBUGS-41935: Sanitize the IgnitionPayload (XSS)
 Author: Juan Manuel Parrilla Madrid <jparrill@redhat.com>
 Date: Fri Sep 13 17:26:47 2024 +0200
 1 file changed, 9 insertions(+)
❯ snyk code test --severity-threshold=high

Testing /home/celebdor/code/openshift/hypershift ...


✔ Test completed

Organization:      celebdor
Test type:         Static code analysis
Project path:      /home/celebdor/code/openshift/hypershift

Summary:

✔ Awesome! No issues were found.`

**Comment by enxebre** [comment]
Thanks for the PR. I hold it but it was too late. I understand it fixes de the snyk warning but I don't think it makes much sense since we own the payloadStore and the additional sanitization is just unmarshalling to map[string]interface{}. I would have required this change to be in a self contained and unit tested function that ideally unmarshalls to a ignition struct with a //doc comment clarifying why is needed.

**Pull request merged**
