### PR TITLE
OCPBUGS-10864: fix external APIServer address selection based on endpointAccess

### PR DESCRIPTION
**Pull request by sjenning**

### CODE REVIEW

**Comment by celebdor** [comment]
/retitle OCPBUGS-10864: fix external APIServer address selection based on endpointAccess

**Comment by sjenning** [comment]
flaked on
```
    nodepool_nto_machineconfig_test.go:151: 
        failed waiting for all pods in the NTO MachineConfig update verification DS to be ready: timed out waiting for the condition
```
/retest-required

**Pull request merged**
