### PR TITLE
HOSTEDCP-1353: Improve description for agent APIServerAddress CLI flag

### PR DESCRIPTION
**Pull request by CrystalChun**
**What this PR does / why we need it**:
Clarifies which API Server Address this flag refers to and adds a warning about being connected to the management cluster if leaving the flag unset.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes # [HOSTEDCP-1353](https://issues.redhat.com/browse/HOSTEDCP-1353)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by avishayt** [comment]
@zanetworker WDYT?

**Comment by zanetworker** [comment]
Looks good, thanks both :)

**Comment by celebdor** [comment]
/retitle OCPBUGS-25857: Improve description for agent APIServerAddress CLI flag

**Pull request merged**
