### PR TITLE
[release-4.16] OCPBUGS-30282: Multiple MachineConfigs in one CM

### PR DESCRIPTION
**Pull request by michael-topchiev**
This PR is a manual cherry-pick of  https://github.com/openshift/hypershift/pull/3695 into branch `release-4.16` because automatic `/cherry-pick` failed due to a code conflict.

### CODE REVIEW

**Comment by jparrill** [comment]
You need to fix the release note :).

/approve

**Comment by michael-topchiev** [comment]
@jparrill the release note is fixed now

**Pull request merged**
