### PR TITLE
OCPBUGS-20033: Fixed transition in olmCatalogPlacement

### PR DESCRIPTION
**Pull request by jparrill**
The transition from/to management from/to guest. Now the remnant pods are properly deleted and catalog sources respect the disableAllDefaultSources from the OperatorHub object in the HostedCluster

**Which issue(s) this PR fixes**:
Fixes #[OCPBUGS-20033](https://issues.redhat.com/browse/OCPBUGS-20033)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
> from/to management from/to guest.

why do we have to support this transition?

**Comment by enxebre** [comment]
Thanks! let's don't support transitioning for now, consider this field immutable and add CEL validation for it until there's known use case that requires otherwise. Then we can revisit. We can always open up but not the other way around.

**Comment by jparrill** [comment]
I understand that this decision may not align entirely with my perspective, but I can appreciate that it might not be the optimal timing for its implementation. I will close this pull request and initiate another one with the CEL validation.

**Pull request closed without merging**
