### PR TITLE
Dockerfile.control-plane fix missing hosted-cluster-config-operator

### PR DESCRIPTION
**Pull request by hardys**
This was removed in #823

### CODE REVIEW

**Comment by hardys** [comment]
/retitle Dockerfile.control-plane fix missing hosted-cluster-config-operator

**Comment by enxebre** [comment]
It seems we are using this in the Dockerfile.control-plane for the CI brew builds, can we make sure we gate PRs on it? cc @ironcladlou

**Comment by hardys** [comment]
Also see related https://github.com/openshift/release/pull/25092

**Comment by alvaroaleman** [comment]
/hold
to make sure https://github.com/openshift/hypershift/pull/836 merges asap

**Comment by ironcladlou** [comment]
Superceded by https://github.com/openshift/hypershift/pull/829

**Pull request closed without merging**
