### PR TITLE
Add CLI command to create AWS infrastructure

### PR DESCRIPTION
**Pull request by csrwng**
Command uses AWS SDK to create infrastructure artifacts required for a cluster.
The output of the command is information needed to create a cluster on AWS.

The idea is that eventually the command will be invoked directly by the `create cluster` command.

Currently we don't have an uninstaller, but you can use existing uninstall tools like the `hiveutil aws-tag-deprovision` command to remove resources created by this command.

### CODE REVIEW

**Comment by enxebre** [comment]
This is cool!

>Currently we don't have an uninstaller, but you can use existing uninstall tools like the hiveutil aws-tag-deprovision command to remove resources created by this command.

Are we planning to have a follow up for uninstall so we don't have to rely on a different CLI?

Seems the command is not logging anything at all atm is it?

**Comment by csrwng** [comment]
> Are we planning to have a follow up for uninstall so we don't have to rely on a different CLI?

Yes I would like to add a destroy command as well

> Seems the command is not logging anything at all atm is it?

It isn't but I can definitely add it.

**Comment by ironcladlou** [comment]
Couple of quick high level observations:

1. In retrospect I think noun/verb is my preference
2. What about a provider specific subcommand (e.g. `infra create aws`), as additional platforms are inevitable

**Comment by ironcladlou** [comment]
Perhaps a more existential point: how confident are we in our ability to make this reliable and idempotent while remaining stateless? I see you're relying on AWS tagging to track resources, but it's not clear that will work for all resources (For example, you can't tag a DNS record in Route53; are there any other examples which will bite us?) Likewise, as we extend into other platforms, we'll have similar concerns. It doesn't look like you're doing fetch/compare prior to creates; what happens now if you run this twice with the same inputs?

I think the [Terraform architecture docs on state](https://www.terraform.io/docs/language/state/purpose.html#mapping-to-the-real-world) cover a lot of the potential challenges with this approach. I just want to make sure we have answers for all the problems that are known to be likely to come up.

**Comment by csrwng** [comment]
@ironcladlou something to keep in mind is that this is a developer tool. Concerns about idempotency are valid, but I think it's something we should deal with when doing this in the product. I still think we should delegate to something else for the happy path; whether that's CAPI or some other framework is still to be determined. 
My goal for this is that we don't grind development to a halt once we require pre-created infra.

**Comment by ironcladlou** [comment]
> @ironcladlou something to keep in mind is that this is a developer tool. Concerns about idempotency are valid, but I think it's something we should deal with when doing this in the product. I still think we should delegate to something else for the happy path; whether that's CAPI or some other framework is still to be determined.
> My goal for this is that we don't grind development to a halt once we require pre-created infra.

Good context, thanks. I would suggest we are careful to ensure that it's both idempotent and also rock solid with its ability to clean up to make it a productive developer/test fixture tool. As far as I know that should be possible for the narrow set of resources we're interested in... I propose going the distance with the initial version of the tool to make sure we're not setting ourselves up for trouble. What do you think?

**Pull request merged**
