### PR TITLE
[release-4.17] OSASINFRA-3572,OSASINFRA-3573: OpenStack backports for ingress

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

- **openstack: Don't allow unsupported --external-dns-domain**
- **openstack: remove support for floating IP**
- **Revert "e2e/util: override CLUSTER_NAME for platform OpenStack"**
- **openstack: handle DNS for ingress in e2e**

These backports are necessary for our CI to test the OpenStack platform dev-preview.

### CODE REVIEW

**Comment by EmilienM** [comment]
/test e2e-openstack
weird, it passed last week

**Comment by EmilienM** [comment]
Failing on `EnsureNoCrashingPods`.

**Comment by EmilienM** [comment]
i'm going to include https://github.com/openshift/hypershift/pull/4669 as well once it's merged

**Comment by mdbooth** [comment]
Assuming the tests pass
/lgtm

**Pull request merged**
