### PR TITLE
fix(cpo): Remove storage from mgmt cluster for IBM Cloud

### PR DESCRIPTION
**Pull request by hasueki**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by hasueki** [comment]
@mkumatag @dharaneeshvrd I've pushed a separate commit to include PowerVS platform as well, PTAL: https://github.com/openshift/hypershift/pull/2007/commits/efae021eb1268538871359c9311046f1a1771c90

**Comment by csrwng** [comment]
/hold
for @mkumatag @dharaneeshvrd to review. Remove if all is good

**Comment by dharaneeshvrd** [comment]
/unhold

Changes looks good to me and tested as well, cso and csi got installed in guest cluster and status is looking good!
Thank you so much @hasueki !!
cc @mkumatag

**Pull request merged**
