### PR TITLE
Upgrade AWS SDK

### PR DESCRIPTION
**Pull request by alvaroaleman**
The version we are currently using is about a year old: https://github.com/aws/aws-sdk-go/releases/tag/v1.40.56

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Comment by enxebre** [comment]
@alvaroaleman was there anything in particular which get you to bump this?
/lgtm

**Comment by alvaroaleman** [comment]
> @alvaroaleman was there anything in particular which get you to bump this?

Only that I found an inconsistency in their error typing (s3 has a concrete `BatchError` that does not implement the generic `BatchError` interface) but it isn't actually fixed with the bump. Since I was looking at it anyways I thought I'd just submit the PR, since it might improve things.

**Pull request merged**
