### PR TITLE
OCPBUGS-30102: Support to disable machine management components

### PR DESCRIPTION
**Pull request by KodieGlosserIBM**
What this PR does / why we need it:
Feature to disable machine management components which includes
cluster-api, cluster-autoscaler & machine-approver by toggling
the annotation hypershift.openshift.io/disable-machine-management: "true"

Which issue(s) this PR fixes (optional, use fixes #<issue_number>(, fixes #<issue_number>, ...) format, where issue_number might be a GitHub issue, or a Jira story:
Fixes https://github.com/openshift/hypershift/issues/2320

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

### CODE REVIEW

**Review by hasueki — APPROVED** [review]
/lgtm

**Comment by hasueki** [comment]
I think initial support for this feature could potentially go in as proposed in this PR. One thing that does come to mind is clean up. If this annotation is toggled on then off, I think it would cause these component's resources to linger. We should look to delete these resources when toggled to off.

cc @sjenning @csrwng

**Comment by sjenning** [comment]
/approve
/lgtm

With the caveat that this annotation should only be set on initial creation.  Adding it after initial create will not remove the components and will cause them to not update on HC upgrade.

**Comment by hasueki** [comment]
/retitle OCPBUGS-30102: Support to disable machine management components

**Comment by KodieGlosserIBM** [comment]
Cherry pick: https://github.com/openshift/hypershift/pull/3670

**Pull request merged**
